### PR TITLE
update container count to 2 in the example ExclamationTopology

### PR DESCRIPTION
**Pull request by huijunw**
Before this PR

```
Total number of containers: 6
Using packing class: com.twitter.heron.packing.roundrobin.ResourceCompliantRRPacking
Container 1
CPU: 1.0, RAM: 563 MB, Disk: 1126 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|  exclaim1 |       1 | 1.0 |      512 |      1024 |
====================================================

Container 2
CPU: 1.0, RAM: 563 MB, Disk: 1126 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|  exclaim1 |       2 | 1.0 |      512 |      1024 |
====================================================

Container 3
CPU: 1.0, RAM: 563 MB, Disk: 1126 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|  exclaim1 |       3 | 1.0 |      512 |      1024 |
====================================================

Container 4
CPU: 1.0, RAM: 563 MB, Disk: 1126 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|  exclaim1 |       4 | 1.0 |      512 |      1024 |
====================================================

Container 5
CPU: 1.0, RAM: 563 MB, Disk: 1126 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|      word |       5 | 1.0 |      512 |      1024 |
====================================================

Container 6
CPU: 1.0, RAM: 563 MB, Disk: 1126 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|      word |       6 | 1.0 |      512 |      1024 |
====================================================
```

After this PR:

```
Total number of containers: 2
Using packing class: com.twitter.heron.packing.roundrobin.ResourceCompliantRRPacking
Container 1
CPU: 3.0, RAM: 1690 MB, Disk: 3379 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|  exclaim1 |       1 | 1.0 |      512 |      1024 |
|  exclaim1 |       3 | 1.0 |      512 |      1024 |
|      word |       5 | 1.0 |      512 |      1024 |
====================================================

Container 2
CPU: 3.0, RAM: 1690 MB, Disk: 3379 MB
====================================================
| component | task ID | CPU | RAM (MB) | disk (MB) |
----------------------------------------------------
|  exclaim1 |       2 | 1.0 |      512 |      1024 |
|  exclaim1 |       4 | 1.0 |      512 |      1024 |
|      word |       6 | 1.0 |      512 |      1024 |
====================================================
```

### CODE REVIEW

**Comment by kramasamy** [comment]
@huijunw - once we have some API that allows for setting the DefaultCpu to lower values per instance - then we can have more instances per containers. Ideally, we should move to a world where instances are assigned the defaults and possibly override by the user. Rest of the calculations such as the number of containers, cpu per container memory per container etc automatically.

**Comment by nlu90** [comment]
@kramasamy @nwangtw @huijunw Any ideas on this PR?

**Comment by nwangtw** [comment]
lgtm. but I am curious about the reason to have this PR.

**Comment by nicknezis** [comment]
Closing this pull request. If you believe the PR is still needed, please leave a comment.

**Pull request closed without merging**
