### PR TITLE
rename "topology master" to "topology manager"

### PR DESCRIPTION
**Pull request by armadillojim**
Howdy! I'm relatively new to Heron, and it seems like a wonderful product. Thanks for all your hard work in developing it!

As a newbie I've been reading through the documentation. One thing caught my eye: the term "topology master". Other components don't use the same word. For example, there are the "metrics manager", "stream manager", and "zoo keeper".

This PR is an attempt to change most occurrences of "master" and "slave" to a different term such as "manager", "primary", "server", "secondary", and so on.  I didn't change every occurrence; for example there are some dependencies on outside projects that use those terms:
* Mesos master/slave in `/vagrant`, `schedulers-mesos-local-mac.md`, and `MesosFrameworkTest.java`
* YARN Application Master in documentation and:
    * `HeronMasterDriver`
    * `heron/schedulers/tests/java/org/apache/heron/scheduler/yarn`
    * `heron/schedulers/src/java/org/apache/heron/scheduler/yarn`
    * `heron/config/src/yaml/conf/yarn/scheduler.yaml`
* storm-compatibility and "master" node of Nimbus

Last, there is the "master" branch in use in this repo and many others.

The edits in this PR have the potential to credit merge conflicts in other open PRs.  I checked all open PRs from 2019 and 2020.  Only five would have conflicts, and hopefully they will be easy to resolve:
- [ ] #3227 line 69 in `RoundRobinPackingV2.java`
- [ ] #3561 changes to `/vagrant`
- [x] #3584 many new uses of master/slave in `heron/tools/admin/src/python/main.py` (moot because #3585 was merged)
- [x] #3585 conflicts only in deletions of changes here
- [x] #3602 a handful of conflicts in use of `tmaster`

There is one remaning TODO:
- [ ] `website2/docs/assets/tmanager.png`.  Does anyone have the SVG source for this image (to make an edit easier)?

I tried to break the edits into more digestible bites by splitting commits among subdirectories.  Hopefully this will make reviewing easier.

Some important questions:
- [ ] did I miss anything?
- [ ] did I break anything?
- [ ] do any external libraries rely on the use of `tmaster` or any such variables?

I haven't done testing yet as the edits here took me much longer than I originally anticipated.  However, I will try my best to do so over the next few days.  Additional eyes are welcome!

### CODE REVIEW

**Comment by huijunwu** [comment]
Hi @armadillojim thanks for the PR.
For the open PRs, I am testing them to see if we can merge them soon.
For website2/docs/assets/tmanager.png, guess @kramasamy has the source. If not, we may redraw it.
Could you try to fix the Travis CI in this PR?

**Comment by nicknezis** [comment]
@armadillojim I've created a branch with fixes to clean up the Travis CI syntax checks. I wasn't able to create a PR for you to pull back into your repo, but hopefully this helps. https://github.com/apache/incubator-heron/tree/armadillojim-master-fix

**Comment by armadillojim** [comment]
@huijunwu Thanks.  I fixed the conflicts from #3602 and #3626 that were merged a few days ago.  I also managed to get the CI up and running locally, and fixed all the linting errors.

@nicknezis Thanks.  I don't see any additional commits in that branch, though, so I went ahead and fixed them here.

**Review by nicknezis — APPROVED** [review]

**Comment by joshfischer1108** [comment]
@armadillojim thank you for the contribution. I apologize for the delay in getting in on this PR..  You can enable or disable style checks on your local without travis if you list a `--config` parameter in your bazel command.

So for mac it would be 
with styles
`bazel build --config=darwin path/to/some/target` 
without styles
`bazel build --config=darwin_nostyle path/to/some/target` 

So for ubuntu it would be 
with styles
`bazel build --config=ubuntu path/to/some/target` 
without styles
`bazel build --config=ubuntu_nostyle path/to/some/target` 

So for debian it would be 
with styles
`bazel build --config=debian path/to/some/target` 
without styles
`bazel build --config=debian_nostyle path/to/some/target` 

Our bazel configuration is [here](https://github.com/apache/incubator-heron/blob/master/tools/bazel.rc)

**Comment by armadillojim** [comment]
@joshfischer1108 Thanks for the tip!  I think, though, that I've made all the edits necessary to pass the complete set of checks.  I've also made commits to keep up with yesterday's merges.  Are things OK to go now?  Looks like @nicknezis approved the changes.

**Review by joshfischer1108 — APPROVED** [review]

**Comment by joshfischer1108** [comment]
@armadillojim Looks good to me (a lot of changes tho).  I think we should let this sit for another day to see if anyone else has any concerns.   @Code0x58 @huijunwu @nwangtw @windhamwong any concerns from you all?

**Comment by huijunwu** [comment]
looks good to me

**Review by huijunwu — APPROVED** [review]

**Pull request merged**
