### PR TITLE
Update Bazel protobuf rules

### LINKED ISSUE #3263: Bazel: Update protobuf build rules
Required for compatibility with Bazel 0.24 and above. Not compatible with https://github.com/bazelbuild/bazel/issues/5831

### PR DESCRIPTION
**Pull request by rohanag12**
Closes #3263

### CODE REVIEW

**Comment by nwangtw** [comment]
Hmm. It seems this integration test is failing with this change?

[2019-05-23 20:31:08 +0000] [31m[ERROR][0m: Checking result failed for 20190523201933_IntegrationTest_SlidingTimeWindow1_c2865994-2284-4b89-8fdd-192cb44ee673 topology :: Traceback (most recent call last):
  File "integration_test/src/python/test_runner/main.py", line 204, in run_test
    return results_checker.check_results()
  File "integration_test/src/python/test_runner/main.py", line 123, in check_results
    return self._compare(expected_results, actual_results)
  File "integration_test/src/python/test_runner/main.py", line 136, in _compare
    raise failure
TestFailure: ('Actual result did not match expected result', None)

**Comment by rohanag12** [comment]
```
~/incubator-heron$ bazel clean
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

~/incubator-heron$ bazel version
Build label: 0.23.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 11 16:47:03 2019 (1552322823)
Build timestamp: 1552322823
Build timestamp as int: 1552322823

~/incubator-heron$ bazel test --test_output=errors --config=ubuntu_nostyle integration_test/...
DEBUG: /home/ubuntu/.cache/bazel/_bazel_rohan/6ae13315cd4f4a72906d48bc12f08d52/external/io_bazel_rules_scala/scala/scala_maven_import_external.bzl:59:9: 'jar_sha256' is deprecated. Please use 'artifact_sha256'
INFO: SHA256 (https://pypi.python.org/packages/d9/03/155b3e67fe35fe5b6f4227a8d9e96a14fda828b18199800d161bcefc1359/requests-2.12.3.tar.gz) = de5d266953875e9647e37ef7bfe6ef1a46ff8ddfe61b5b3652edf7ea717ee2b2
DEBUG: Rule 'requests_src' modified arguments {"sha256": "de5d266953875e9647e37ef7bfe6ef1a46ff8ddfe61b5b3652edf7ea717ee2b2"}
INFO: SHA256 (https://pypi.python.org/packages/68/13/1bfbfbd86560e61fa9803d241084fff41a775bf56ee8b3ad72fc9e550dad/setuptools-31.0.0.tar.gz) = 0818cc0de692c3a5c83ca83aa7ec7ba6bc206f278735f1e0267b8d0e095cfe7a
DEBUG: Rule 'setuptools_src' modified arguments {"sha256": "0818cc0de692c3a5c83ca83aa7ec7ba6bc206f278735f1e0267b8d0e095cfe7a"}
INFO: SHA256 (https://pypi.python.org/packages/3a/1d/cd41cd3765b78a4353bbf27d18b099f7afbcd13e7f2dc9520f304ec8981c/pex-1.2.15.tar.gz) = 0147d19123340677b9793b00ec86fe65b6697db3ec99afb796da2300ae5fec14
DEBUG: Rule 'pex_src' modified arguments {"sha256": "0147d19123340677b9793b00ec86fe65b6697db3ec99afb796da2300ae5fec14"}
INFO: SHA256 (https://pypi.python.org/packages/c9/1d/bd19e691fd4cfe908c76c429fe6e4436c9e83583c4414b54f6c85471954a/wheel-0.29.0.tar.gz) = 1ebb8ad7e26b448e9caa4773d2357849bf80ff9e313964bcaf79cbf0201a1648
DEBUG: Rule 'wheel_src' modified arguments {"sha256": "1ebb8ad7e26b448e9caa4773d2357849bf80ff9e313964bcaf79cbf0201a1648"}
INFO: Analysed 28 targets (90 packages loaded, 2178 targets configured).
INFO: From scala //heron/api/src/scala:api-scala:
warning: there was one deprecation warning (since 2.12.0); re-run with -deprecation for details
one warning found
INFO: Elapsed time: 292.425s, Critical Path: 78.00s
INFO: 497 processes: 450 local, 47 worker.
INFO: Build completed successfully, 541 total actions
INFO: Build completed successfully, 541 total actions
```

I tried running the tests locally, they all pass. Maybe it is one of the flaky tests? I'll merge master and push, to re-trigger travis CI.

**Comment by nwangtw** [comment]
> ```
> ~/incubator-heron$ bazel clean
> Starting local Bazel server and connecting to it...
> INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
> 
> ~/incubator-heron$ bazel version
> Build label: 0.23.2
> Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Mon Mar 11 16:47:03 2019 (1552322823)
> Build timestamp: 1552322823
> Build timestamp as int: 1552322823
> 
> ~/incubator-heron$ bazel test --test_output=errors --config=ubuntu_nostyle integration_test/...
> DEBUG: /home/ubuntu/.cache/bazel/_bazel_rohan/6ae13315cd4f4a72906d48bc12f08d52/external/io_bazel_rules_scala/scala/scala_maven_import_external.bzl:59:9: 'jar_sha256' is deprecated. Please use 'artifact_sha256'
> INFO: SHA256 (https://pypi.python.org/packages/d9/03/155b3e67fe35fe5b6f4227a8d9e96a14fda828b18199800d161bcefc1359/requests-2.12.3.tar.gz) = de5d266953875e9647e37ef7bfe6ef1a46ff8ddfe61b5b3652edf7ea717ee2b2
> DEBUG: Rule 'requests_src' modified arguments {"sha256": "de5d266953875e9647e37ef7bfe6ef1a46ff8ddfe61b5b3652edf7ea717ee2b2"}
> INFO: SHA256 (https://pypi.python.org/packages/68/13/1bfbfbd86560e61fa9803d241084fff41a775bf56ee8b3ad72fc9e550dad/setuptools-31.0.0.tar.gz) = 0818cc0de692c3a5c83ca83aa7ec7ba6bc206f278735f1e0267b8d0e095cfe7a
> DEBUG: Rule 'setuptools_src' modified arguments {"sha256": "0818cc0de692c3a5c83ca83aa7ec7ba6bc206f278735f1e0267b8d0e095cfe7a"}
> INFO: SHA256 (https://pypi.python.org/packages/3a/1d/cd41cd3765b78a4353bbf27d18b099f7afbcd13e7f2dc9520f304ec8981c/pex-1.2.15.tar.gz) = 0147d19123340677b9793b00ec86fe65b6697db3ec99afb796da2300ae5fec14
> DEBUG: Rule 'pex_src' modified arguments {"sha256": "0147d19123340677b9793b00ec86fe65b6697db3ec99afb796da2300ae5fec14"}
> INFO: SHA256 (https://pypi.python.org/packages/c9/1d/bd19e691fd4cfe908c76c429fe6e4436c9e83583c4414b54f6c85471954a/wheel-0.29.0.tar.gz) = 1ebb8ad7e26b448e9caa4773d2357849bf80ff9e313964bcaf79cbf0201a1648
> DEBUG: Rule 'wheel_src' modified arguments {"sha256": "1ebb8ad7e26b448e9caa4773d2357849bf80ff9e313964bcaf79cbf0201a1648"}
> INFO: Analysed 28 targets (90 packages loaded, 2178 targets configured).
> INFO: From scala //heron/api/src/scala:api-scala:
> warning: there was one deprecation warning (since 2.12.0); re-run with -deprecation for details
> one warning found
> INFO: Elapsed time: 292.425s, Critical Path: 78.00s
> INFO: 497 processes: 450 local, 47 worker.
> INFO: Build completed successfully, 541 total actions
> INFO: Build completed successfully, 541 total actions
> ```
> 
> I tried running the tests locally, they all pass. Maybe it is one of the flaky tests? I'll merge master and push, to re-trigger travis CI.

I tried to restart the build a few times and it kept failing. It is strange though that the test doesn't look related to the change. Let me trigger the build again.

**Comment by nwangtw** [comment]
finally passed~

**Pull request merged**
