### PR TITLE
[DO NOT MERGE] upgrade to bazel 0.4.4

### PR DESCRIPTION
**Pull request by kramasamy**
Upgrade to compile with bazel 0.4.4. This upgrade is straightforward and we don't want to get too behind in bazel.

### CODE REVIEW

**Comment by huijunw** [comment]
link to https://github.com/twitter/heron/issues/1769

**Comment by billonahill** [comment]
@huijunw we can't merge this until after a new bazel version is published within Twitter and it's been tested in Twitter CI. This change will require coordination.

**Comment by maosongfu** [comment]
Please DON'T MERGE this pull request since it is not tested and could potentially break twitter ci building.

**Comment by huijunwu** [comment]
#1776 replaced this pr.

**Comment by nicknezis** [comment]
#3510 replaces this PR

**Pull request closed without merging**
