### PR TITLE
Revert "Migrate to python3"

### PR DESCRIPTION
**Pull request by nicknezis**
This reverts commit e9f9f5e8ab14f249c7c757c61943b1736484913d.

This PR reverts #3431 due to issues with compilation, testing and runtime issues discovered.

### CODE REVIEW

**Comment by joshfischer1108** [comment]
Hey Nick.  #3431 shows 274 file changes. This one only shows 272.

**Comment by nicknezis** [comment]
I made a fresh clone, checked out a new branch and then ran 'git revert'
with the commit hash from the merge point of the old pull request. I'm not
sure why there would be a difference.

**Comment by nicknezis** [comment]
Updated the branch to now revert the proper commit: 257b1a439588a22b2d7959338ce7be50b02c4708

**Comment by joshfischer1108** [comment]
I'm not sure why it's showing two Travis build statuses.  But the most recent build looks good and the revert also looks good to me.

**Pull request merged**
