### PR TITLE
Upgrade to Python3 for the whole repo

### PR DESCRIPTION
**Pull request by nlu90**
Python2 has been sunsetting: https://pythonclock.org/

We also need to upgrade from python2  to python3.

### CODE REVIEW

**Comment by nlu90** [comment]
This is a follow-up PR for #3412

**Comment by joshfischer1108** [comment]
I noticed travis only has the python package 2.7 listed.  Will this be a problem? https://github.com/apache/incubator-heron/blob/ab9c205a783d6e8b43144560080f2d75b9354145/.travis.yml#L22

**Comment by nlu90** [comment]
> I noticed travis only has the python package 2.7 listed. Will this be a problem?
> 
> https://github.com/apache/incubator-heron/blob/ab9c205a783d6e8b43144560080f2d75b9354145/.travis.yml#L22

@joshfischer1108 Yeah, ideally we also need to update the travis config file. I will add a new commit and see how things work.

**Comment by nlu90** [comment]
@joshfischer1108 With the Travis change, the ci job still passes

**Comment by joshfischer1108** [comment]
@nlu90 That's fantastic.  Nice work.

**Comment by nicknezis** [comment]
Should the `compile` and `dist` Dockerfiles also be updated to include the right Python packages?

**Pull request merged**
