### PR TITLE
Update zk version to 3.4.14 in dist and install zk in ubuntu 16/18 di…

### PR DESCRIPTION
**Pull request by nwangtw**
…st docker image

### CODE REVIEW

**Comment by nicknezis** [comment]
Looks good to me, but is there any value in keeping the Zookeeper version as a Docker build ARG? This change would lose that feature. Probably not a big deal.

**Comment by nwangtw** [comment]
> Looks good to me, but is there any value in keeping the Zookeeper version as a Docker build ARG? This change would lose that feature. Probably not a big deal.

How it was used? It should be easy to add back.

**Comment by joshfischer1108** [comment]
Overall this looks good to me.  Straight forward and easy to read.  I noticed several of the same changes in the different files for different distros which got me thinking.  Do we really need to support all of these different versions of ubuntu containers?  Or even further do we need to support  ubunutu, centos, and debian?  Wouldn't it be more efficient for us to have one "official" supported image?

**Comment by nwangtw** [comment]
> Overall this looks good to me. Straight forward and easy to read. I noticed several of the same changes in the different files for different distros which got me thinking. Do we really need to support all of these different versions of ubuntu containers? Or even further do we need to support ubunutu, centos, and debian? Wouldn't it be more efficient for us to have one "official" supported image?

Agreed. This is a reasonable question to discuss.

**Pull request merged**
