### PR TITLE
(Ok To Merge) updating docker scripts

### PR DESCRIPTION
**Pull request by joshfischer1108**
This PR is only for feedback in updating the Heron Docker build scripts.

@kramasamy In the process of trying to diagnose other issues, I noticed the docker build scripts are not working as of today.  I made a few changes and was able to successfully build a Heron Ubuntu 14.04 image and place it in a zip file.  I think that I could easily make these changes to the other image types if you think these changes are ok to put in.  

Let me know your thoughts.

### CODE REVIEW

**Comment by joshfischer1108** [comment]
To verify these changes execute
```bash 
$ ./docker/scripts/build-artifacts.sh ubuntu14.04 0.19.0 ~/local-heron-release/
$ ./docker/scripts/build-docker.sh ubuntu14.04 0.19.0 ~/local-heron-release/
```

**Comment by joshfischer1108** [comment]
This build failed because of an integration test.  I don't see a way to kick off the build anymore.  Seems the button was removed.

**Comment by joshfischer1108** [comment]
looking over, I found in error in my docker config.  

```Step 1/19 : FROM ubuntu:14.04
 ---> 578c3e61a98c
Step 2/19 : RUN apt-get -y update && apt-get -y install     python     unzip     software-properties-common     supervisor     curl &&     apt-get clean all
 ---> Using cache
 ---> b7292a142da0
Step 3/19 : RUN add-apt-repository ppa:openjdk-r/ppa && apt-get -y update &&     apt-get -y install openjdk-8-jdk && apt-get clean all
 ---> Using cache
 ---> dbdc059747ff
Step 4/19 : ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
 ---> Using cache
 ---> 3632db9a55cb
Step 5/19 : RUN update-ca-certificates -f
 ---> Using cache
 ---> a8870c88f73e
Step 6/19 : ADD artifacts /heron
 ---> Using cache
 ---> 8c3fb38e66ee
Step 7/19 : WORKDIR /heron
 ---> Using cache
 ---> 01f1def45d52
Step 8/19 : RUN /heron/heron-client-install.sh && /heron/heron-tools-install.sh
 ---> Running in a341c5438a1a
/bin/sh: 1: /heron/heron-client-install.sh: not found
The command '/bin/sh -c /heron/heron-client-install.sh && /heron/heron-tools-install.sh' returned a non-zero code: 127
````
I'll look into this more this weekend.

**Comment by kramasamy** [comment]
Looks good to me - let us merge it once the CI passes.

**Comment by joshfischer1108** [comment]
@kramasamy I went ahead and updated the other  docker images as well.  I think we are good to go.

**Comment by joshfischer1108** [comment]
@kramasamy After doing further investigation.  This PR does fix the broken docker references to the install scripts, but it does not fix the other os specific issues that need to be addressed.  It's up to you if you decide you want to merge.

**Pull request merged**
