### PR TITLE
Adding support of docker build for debian10

### PR DESCRIPTION
**Pull request by windhamwong**
The docker build for debian10 includes:
- Using openjdk8 debian10 image, openjdk:8u242-jre-slim-buster
- Default install Python3.7
- Adding few lines of description of how to compile docker
- Changing the example version to latest, to match the naming format

### CODE REVIEW

**Comment by joshfischer1108** [comment]
@windhamwong Thank you for the start of this pull request.  I was in the process of working through of getting a Debian 9 Heron container ready for for the next release.  Do you have a time estimate of when  you think your contribution will be complete?  I may hold off working on the Debian9 container if you feel that you are not far off from getting this ready for review.

**Comment by windhamwong** [comment]
oh interesting situation. I am trying debian10 because debian9 docker build doesn't support Python 3.6+ due to lack of python-dev for 3.6+ version. (Or maybe I can sort out the source build thing but I can't find the source link) Let me try both debian9 and debian10 and come back :)

My debian10 commit is still having a huge break due to issue of protobuf bazel build. That's why the PR is still in draft.

**Comment by joshfischer1108** [comment]
Well I wouldn't say the container is perfect yet.  There is still some debugging to do. For example, I had to add in some flags when compiling the zookeeper target.. On mac it passes on Debian9 it fails because the warnings that are thrown are treated as errors.   I'm not exactly sure why yet.  After adding those flags I was able to build a Debian9 container and submit an example ECO topology successfully.   You can find the branch in this repo.. It is -> `joshfischer/debian9`.

**Comment by windhamwong** [comment]
I didn't put any env or config for building docker. I believe if you see the warnings are treated as error, that means there is a major error before this line. The docker build is quite slow and I am reverting to debian9 build now as debian10 + protobuf update +python37 fails due to lack of library build (need time to build and fix).
I will come back when I have finished my build.

**Comment by windhamwong** [comment]
Ok, I am working on debian9 now with the master configs. I do have an error here, 

`
08:54:42 [WARN] /root/.cache/pants/setup/bootstrap-Linux-x86_64/1.23.0_py37/lib/python3.7/site-packages/pex/pep425tags.py:274: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
`

Is this the error you got?

**Comment by windhamwong** [comment]
[Unrelated to the PR]
I have successfully deploy Python3.7.3 with Python37-dev to debian9. I am currently fixing the imp version.

[Related to PR]
The debian10 is having issue with bazel. I might retry again later to fix the issue before officially submit PR.

**Comment by windhamwong** [comment]
Will merge with PR #3438 .

**Pull request closed without merging**
