### PR TITLE
Bazel: Update pex rules for compatibility with 0.27

### PR DESCRIPTION
**Pull request by rohanag12**
Updates to Python/PEX rules for Bazel compatibility.

### CODE REVIEW

**Comment by rohanag12** [comment]
@nwangtw @joshfischer1108 Can you please restart the build? Failed on one of the integration tests, as usual. I'll look into removing this flakiness if I get some time.

**Comment by joshfischer1108** [comment]
Sure. I just restarted it.

**Comment by joshfischer1108** [comment]
@rohanag12  It doesn't look like you changed the Bazel version in this PR.  Is it safe to assume this is just prep work for `0.27`?

The changes look good to me.. @nlu90 You good with this?

**Comment by rohanag12** [comment]
Yes, this is just updating the PEX rules. There are a few more changes needed to other rules, I'll send a separate pull request.

**Pull request merged**
