### PR TITLE
Support Java 11

### PR DESCRIPTION
**Pull request by nwangtw**
Compiles ok with Java 11

### CODE REVIEW

**Comment by nwangtw** [comment]
https://github.com/apache/incubator-heron/issues/3266

**Comment by joshfischer1108** [comment]
You might need to update the JDK version in the travis file too. https://github.com/apache/incubator-heron/blob/master/.travis.yml

**Comment by nwangtw** [comment]
> You might need to update the JDK version in the travis file too. https://github.com/apache/incubator-heron/blob/master/.travis.yml

The change should work for Java8 and above

**Comment by nwangtw** [comment]
Some unit test libraries are not Jdk11 compatible and need to be updated. :(

**Comment by joshfischer1108** [comment]
It might be better to move this branch from your forked repo into the main heron repo.  This way people can help us complete this task by opening up PR's directly to this branch.

**Comment by nwangtw** [comment]
> It might be better to move this branch from your forked repo into the main heron repo. This way people can help us complete this task by opening up PR's directly to this branch.

Ah, interesting. That is a great idea~ 

Pushed to java_11_support branch.
To https://github.com/twitter/heron.git
 * [new branch]      java_11_support -> java_11_support

**Comment by thinker0** [comment]
https://github.com/apache/incubator-heron/blob/master/heron/executor/src/python/heron_executor.py#L436-L449

https://github.com/apache/incubator-heron/blob/master/heron/executor/src/python/heron_executor.py#L476-L490

From 1.9 and above, it should change as follows.

```
-Xlog:gc=info:file=${APP}/logs/gc.log.$(/bin/date +%Y-%m-%d-%H%M%S):time,uptime,pid:filecount=5,filesize=4096
```

- https://medium.com/hotels-com-technology/what-to-do-about-the-garbage-collector-when-moving-from-java-8-to-java-11-71e60f9b81f
- https://dzone.com/articles/disruptive-changes-to-gc-logging-in-java-9

**Comment by thinker0** [comment]
#3399

**Comment by thinker0** [comment]
#3434

**Comment by nicknezis** [comment]
Can this Pull Request be closed due to the work done by @thinker0 in #3399 and #3434 ?

**Pull request closed without merging**
