### PR TITLE
#974 update slf4j version from 1.7.7 to latest 1.7.21

### PR DESCRIPTION
**Pull request by caofangkun**
slf4j creates warning messages on stderr like following:

```
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositorySystem
SLF4J: org.eclipse.aether.internal.impl.DefaultMetadataResolver
SLF4J: org.apache.maven.repository.internal.DefaultVersionResolver
```

update SLF4J version from 1.7.7 to latest 1.7.21 is likely to solve this issue.

### CODE REVIEW

**Comment by kramasamy** [comment]
@caofangkun - When I run this, I get the following:

```
[tw-mbp-kramasamy heron24 (heron-974)]$ bazel build --config=darwin heron/...
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositorySystem
SLF4J: org.eclipse.aether.internal.impl.DefaultRemoteRepositoryManager
SLF4J: org.eclipse.aether.internal.impl.DefaultTransporterProvider
SLF4J: org.apache.maven.repository.internal.DefaultVersionResolver
SLF4J: org.eclipse.aether.transport.file.FileTransporter
SLF4J: org.eclipse.aether.internal.impl.DefaultArtifactResolver
SLF4J: org.apache.maven.repository.internal.DefaultArtifactDescriptorReader
SLF4J: org.eclipse.aether.internal.impl.DefaultMetadataResolver
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider
SLF4J: org.eclipse.aether.transport.http.HttpTransporter
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher
SLF4J: org.eclipse.aether.internal.impl.DefaultOfflineController
SLF4J: org.eclipse.aether.internal.impl.DefaultUpdatePolicyAnalyzer
SLF4J: org.apache.maven.repository.internal.DefaultVersionRangeResolver
SLF4J: org.eclipse.aether.internal.impl.DefaultUpdateCheckManager
SLF4J: org.eclipse.aether.connector.basic.BasicRepositoryConnector
```

**Comment by caofangkun** [comment]
@kramasamy  
Do you clean up before build ? Could you try as following again?
```
➜  twitter-heron git:(heron-974) bazel clean --expunge    
➜  twitter-heron git:(heron-974) bazel build --config=darwin heron/...   
```

**Comment by kramasamy** [comment]
Hmm... still i am getting this. Note that I am using Mac

```
[tw-mbp-kramasamy heron24 (heron-974)]$ bazel clean --expunge 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
[tw-mbp-kramasamy heron24 (heron-974)]$ bazel build --config=darwin heron/...
.
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositorySystem
SLF4J: org.eclipse.aether.internal.impl.DefaultRemoteRepositoryManager
SLF4J: org.eclipse.aether.internal.impl.DefaultTransporterProvider
SLF4J: org.apache.maven.repository.internal.DefaultVersionResolver
SLF4J: org.eclipse.aether.transport.file.FileTransporter
SLF4J: org.eclipse.aether.internal.impl.DefaultMetadataResolver
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider
SLF4J: org.eclipse.aether.transport.http.HttpTransporter
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositoryEventDispatcher
SLF4J: org.eclipse.aether.internal.impl.DefaultUpdatePolicyAnalyzer
SLF4J: org.eclipse.aether.internal.impl.DefaultUpdateCheckManager
SLF4J: org.eclipse.aether.connector.basic.BasicRepositoryConnector
```

**Comment by kramasamy** [comment]
@supunkamburugamuve - can you try this if you get a chance?

**Comment by kramasamy** [comment]
@caofangkun - wondering if you are facing the issue that I am facing.

**Comment by caofangkun** [comment]
Hi @kramasamy 
I‘m using Ubuntu, and did show no more warning messages when I updated slf4j version. 
I do not have a mac -_-#! ,so I couldn't figure out what happening on Mac.

**Comment by nicknezis** [comment]
Will be fixed by #3510 . Thank for for finding this.

**Pull request closed without merging**
