### PR TITLE
[Streamlet Scala API] Add Scala Streamlet Integration Tests Part II

### PR DESCRIPTION
**Pull request by erenavsarogullari**
This PR aims the following changes:

Adding new Scala Streamlet Integration Test as `ScalaStreamletWithMapAndFlatMapAndFilterAndClone`

### CODE REVIEW

**Comment by erenavsarogullari** [comment]
cc @kramasamy @nwangtw

**Comment by kramasamy** [comment]
Will take a look in an hour

**Comment by erenavsarogullari** [comment]
Thanks @kramasamy. Not urgent, just notification ;)

**Comment by erenavsarogullari** [comment]
@kramasamy @nwangtw 
This PR is ready to review / merge. Thanks in advance ;)

**Pull request merged**
