### PR TITLE
[Heron 3707]  ConfigMap Pod Template Support Documentation

### PR DESCRIPTION
**Pull request by surahman**
**_Issue #3707:_**

Documentation for Pod Templates in `ConfigMap`s. The issue tracking this feature is #3710.

### CODE REVIEW

**Comment by surahman** [comment]
Hi @joshfischer1108, I have created a very quick document outlining usage. There was an issue I found in the way I have handled looking up the Pod Templates but I will write that up in #3710.

**Comment by nicknezis** [comment]
This is great. I'll be adding a similar document for the last Kubernetes scheduler feature I added. 

Not asking you to do this refactor, but mentioning it to share the idea... I would like to combine the Kubernetes related documentation into a single page under the Schedulers menu. Then we can have sub-menu items for the various aspects of this scheduler. Something similar to this [Spark document](https://spark.apache.org/docs/latest/running-on-kubernetes.html).

**Comment by surahman** [comment]
I have updated the instructions for the `CONFIGMAP-NAME.POD-TEMPLATE-NAME` change.

**Comment by surahman** [comment]
**_TODO:_** as per @nicknezis  suggestion, list the parts of the PodTemplate that will be replaced and the config items that can be used to set them (i.e. Env variables, labels, annotations).

**Comment by surahman** [comment]
Updated, please feel free to add detail and make adjustments through GH review.

**Review by joshfischer1108 — APPROVED** [review]

**Comment by surahman** [comment]
Thank you @joshfischer1108, I  really appreciate your time and effort!

**Pull request merged**
