### PR TITLE
Java 11 support

### PR DESCRIPTION
**Pull request by thinker0**
I use it in mesos/aurora, so I think I should go to jdk11 because jdk11 supports CGROUP Container well. jdk8 is not suitable for container.

#3382 #3399

### CODE REVIEW

**Comment by nicknezis** [comment]
We should also update all of the Dockerfiles for compile and dist as needed.

**Comment by thinker0** [comment]
```

================================================================================
INFO: Elapsed time: 2395.926s, Critical Path: 436.06s
INFO: 4055 processes: 3714 local, 341 worker.
INFO: Build completed successfully, 7027 total actions
//heron/api/tests/cpp:serialization_unittest                             PASSED in 0.1s
//heron/api/tests/java:BaseWindowedBoltTest                              PASSED in 2.2s
//heron/api/tests/java:ConfigTest                                        PASSED in 1.6s
//heron/api/tests/java:CountStatAndMetricTest                            PASSED in 1.8s
//heron/api/tests/java:GeneralReduceByKeyAndWindowOperatorTest           PASSED in 2.4s
//heron/api/tests/java:HeronSubmitterTest                                PASSED in 6.4s
//heron/api/tests/java:JoinOperatorTest                                  PASSED in 3.2s
//heron/api/tests/java:KVStreamletShadowTest                             PASSED in 1.5s
//heron/api/tests/java:KeyByOperatorTest                                 PASSED in 3.1s
//heron/api/tests/java:LatencyStatAndMetricTest                          PASSED in 1.7s
//heron/api/tests/java:ReduceByKeyAndWindowOperatorTest                  PASSED in 3.3s
//heron/api/tests/java:StreamletImplTest                                 PASSED in 2.5s
//heron/api/tests/java:StreamletShadowTest                               PASSED in 1.6s
//heron/api/tests/java:StreamletUtilsTest                                PASSED in 2.7s
//heron/api/tests/java:UtilsTest                                         PASSED in 0.9s
//heron/api/tests/java:WaterMarkEventGeneratorTest                       PASSED in 2.1s
//heron/api/tests/java:WindowManagerTest                                 PASSED in 1.5s
//heron/api/tests/java:WindowedBoltExecutorTest                          PASSED in 1.9s
//heron/api/tests/scala:api-scala-test                                   PASSED in 6.6s
//heron/ckptmgr/tests/java:CheckpointManagerServerTest                   PASSED in 3.3s
//heron/common/tests/cpp/basics:fileutils_unittest                       PASSED in 0.2s
//heron/common/tests/cpp/basics:rid_unittest                             PASSED in 0.1s
//heron/common/tests/cpp/basics:strutils_unittest                        PASSED in 0.2s
//heron/common/tests/cpp/basics:utils_unittest                           PASSED in 0.2s
//heron/common/tests/cpp/config:topology-config-helper_unittest          PASSED in 0.2s
//heron/common/tests/cpp/errors:errors_unittest                          PASSED in 0.2s
//heron/common/tests/cpp/errors:module_unittest                          PASSED in 0.1s
//heron/common/tests/cpp/errors:syserrs_unittest                         PASSED in 0.3s
//heron/common/tests/cpp/metrics:count-metric_unittest                   PASSED in 0.3s
//heron/common/tests/cpp/metrics:mean-metric_unittest                    PASSED in 0.1s
//heron/common/tests/cpp/metrics:multi-count-metric_unittest             PASSED in 0.1s
//heron/common/tests/cpp/metrics:multi-mean-metric_unittest              PASSED in 0.3s
//heron/common/tests/cpp/metrics:time-spent-metric_unittest              PASSED in 1.6s
//heron/common/tests/cpp/network:http_unittest                           PASSED in 0.7s
//heron/common/tests/cpp/network:order_unittest                          PASSED in 0.4s
//heron/common/tests/cpp/network:packet_unittest                         PASSED in 0.1s
//heron/common/tests/cpp/network:piper_unittest                          PASSED in 2.1s
//heron/common/tests/cpp/network:rate_limit_unittest                     PASSED in 4.3s
//heron/common/tests/cpp/network:switch_unittest                         PASSED in 0.8s
//heron/common/tests/cpp/threads:spcountdownlatch_unittest               PASSED in 2.2s
//heron/common/tests/java:ByteAmountTest                                 PASSED in 1.2s
//heron/common/tests/java:CommunicatorTest                               PASSED in 1.0s
//heron/common/tests/java:ConfigReaderTest                               PASSED in 1.8s
//heron/common/tests/java:EchoTest                                       PASSED in 2.7s
//heron/common/tests/java:FileUtilsTest                                  PASSED in 6.6s
//heron/common/tests/java:HeronServerTest                                PASSED in 3.1s
//heron/common/tests/java:PackageTypeTest                                PASSED in 1.0s
//heron/common/tests/java:SysUtilsTest                                   PASSED in 6.9s
//heron/common/tests/java:SystemConfigTest                               PASSED in 1.5s
//heron/common/tests/java:TopologyUtilsTest                              PASSED in 2.2s
//heron/common/tests/java:WakeableLooperTest                             PASSED in 2.3s
//heron/common/tests/python/pex_loader:pex_loader_unittest               PASSED in 2.3s
//heron/downloaders/tests/java:DLDownloaderTest                          PASSED in 4.0s
//heron/downloaders/tests/java:ExtractorTests                            PASSED in 1.6s
//heron/downloaders/tests/java:RegistryTest                              PASSED in 1.3s
//heron/executor/tests/python:executor_unittest                          PASSED in 2.2s
//heron/healthmgr/tests/java:BackPressureDetectorTest                    PASSED in 2.8s
//heron/healthmgr/tests/java:BackPressureSensorTest                      PASSED in 2.9s
//heron/healthmgr/tests/java:BufferSizeSensorTest                        PASSED in 2.3s
//heron/healthmgr/tests/java:DataSkewDiagnoserTest                       PASSED in 3.0s
//heron/healthmgr/tests/java:ExecuteCountSensorTest                      PASSED in 4.0s
//heron/healthmgr/tests/java:GrowingWaitQueueDetectorTest                PASSED in 3.6s
//heron/healthmgr/tests/java:HealthManagerTest                           PASSED in 5.3s
//heron/healthmgr/tests/java:HealthPolicyConfigReaderTest                PASSED in 1.3s
//heron/healthmgr/tests/java:LargeWaitQueueDetectorTest                  PASSED in 3.3s
//heron/healthmgr/tests/java:MetricsCacheMetricsProviderTest             PASSED in 3.9s
//heron/healthmgr/tests/java:PackingPlanProviderTest                     PASSED in 3.2s
//heron/healthmgr/tests/java:ProcessingRateSkewDetectorTest              PASSED in 1.7s
//heron/healthmgr/tests/java:ScaleUpResolverTest                         PASSED in 2.9s
//heron/healthmgr/tests/java:SlowInstanceDiagnoserTest                   PASSED in 2.5s
//heron/healthmgr/tests/java:UnderProvisioningDiagnoserTest              PASSED in 1.7s
//heron/healthmgr/tests/java:WaitQueueSkewDetectorTest                   PASSED in 6.2s
//heron/instance/tests/java:ActivateDeactivateTest                       PASSED in 2.5s
//heron/instance/tests/java:BoltInstanceTest                             PASSED in 2.7s
//heron/instance/tests/java:BoltStatefulInstanceTest                     PASSED in 5.0s
//heron/instance/tests/java:ConnectTest                                  PASSED in 3.5s
//heron/instance/tests/java:CustomGroupingTest                           PASSED in 3.3s
//heron/instance/tests/java:EmitDirectBoltTest                           PASSED in 3.8s
//heron/instance/tests/java:EmitDirectSpoutTest                          PASSED in 2.7s
//heron/instance/tests/java:GlobalMetricsTest                            PASSED in 1.1s
//heron/instance/tests/java:HandleReadTest                               PASSED in 4.5s
//heron/instance/tests/java:HandleWriteTest                              PASSED in 8.3s
//heron/instance/tests/java:MultiAssignableMetricTest                    PASSED in 1.2s
//heron/instance/tests/java:SpoutInstanceTest                            PASSED in 4.5s
//heron/instance/tests/java:SpoutStatefulInstanceTest                    PASSED in 4.7s
//heron/instance/tests/python/network:event_looper_unittest              PASSED in 4.2s
//heron/instance/tests/python/network:gateway_looper_unittest            PASSED in 11.9s
//heron/instance/tests/python/network:heron_client_unittest              PASSED in 2.7s
//heron/instance/tests/python/network:metricsmgr_client_unittest         PASSED in 2.6s
//heron/instance/tests/python/network:protocol_unittest                  PASSED in 2.7s
//heron/instance/tests/python/network:st_stmgrcli_unittest               PASSED in 2.1s
//heron/instance/tests/python/utils:communicator_unittest                PASSED in 2.2s
//heron/instance/tests/python/utils:custom_grouping_unittest             PASSED in 2.4s
//heron/instance/tests/python/utils:global_metrics_unittest              PASSED in 3.8s
//heron/instance/tests/python/utils:log_unittest                         PASSED in 2.2s
//heron/instance/tests/python/utils:metrics_helper_unittest              PASSED in 2.5s
//heron/instance/tests/python/utils:outgoing_tuple_helper_unittest       PASSED in 2.0s
//heron/instance/tests/python/utils:pplan_helper_unittest                PASSED in 6.3s
//heron/instance/tests/python/utils:py_metrics_unittest                  PASSED in 2.0s
//heron/instance/tests/python/utils:topology_context_impl_unittest       PASSED in 2.2s
//heron/instance/tests/python/utils:tuple_helper_unittest                PASSED in 1.9s
//heron/io/dlog/tests/java:DLInputStreamTest                             PASSED in 2.8s
//heron/io/dlog/tests/java:DLOutputStreamTest                            PASSED in 1.6s
//heron/metricscachemgr/tests/java:CacheCoreTest                         PASSED in 2.1s
//heron/metricscachemgr/tests/java:MetricsCacheQueryUtilsTest            PASSED in 2.0s
//heron/metricscachemgr/tests/java:MetricsCacheTest                      PASSED in 3.2s
//heron/metricsmgr/tests/java:FileSinkTest                               PASSED in 2.6s
//heron/metricsmgr/tests/java:HandleTMasterLocationTest                  PASSED in 3.4s
//heron/metricsmgr/tests/java:MetricsCacheSinkTest                       PASSED in 11.7s
//heron/metricsmgr/tests/java:MetricsManagerServerTest                   PASSED in 2.4s
//heron/metricsmgr/tests/java:MetricsUtilTests                           PASSED in 1.5s
//heron/metricsmgr/tests/java:PrometheusSinkTests                        PASSED in 2.2s
//heron/metricsmgr/tests/java:SinkExecutorTest                           PASSED in 1.7s
//heron/metricsmgr/tests/java:TMasterSinkTest                            PASSED in 11.6s
//heron/metricsmgr/tests/java:WebSinkTest                                PASSED in 2.1s
//heron/packing/tests/java:FirstFitDecreasingPackingTest                 PASSED in 2.2s
//heron/packing/tests/java:PackingPlanBuilderTest                        PASSED in 2.9s
//heron/packing/tests/java:PackingUtilsTest                              PASSED in 2.1s
//heron/packing/tests/java:ResourceCompliantRRPackingTest                PASSED in 2.6s
//heron/packing/tests/java:RoundRobinPackingTest                         PASSED in 3.0s
//heron/packing/tests/java:ScorerTest                                    PASSED in 1.2s
//heron/scheduler-core/tests/java:HttpServiceSchedulerClientTest         PASSED in 6.1s
//heron/scheduler-core/tests/java:JsonFormatterUtilsTest                 PASSED in 1.9s
//heron/scheduler-core/tests/java:LaunchRunnerTest                       PASSED in 5.0s
//heron/scheduler-core/tests/java:LauncherUtilsTest                      PASSED in 7.6s
//heron/scheduler-core/tests/java:LibrarySchedulerClientTest             PASSED in 2.7s
//heron/scheduler-core/tests/java:RuntimeManagerMainTest                 PASSED in 9.6s
//heron/scheduler-core/tests/java:RuntimeManagerRunnerTest               PASSED in 14.1s
//heron/scheduler-core/tests/java:SchedulerClientFactoryTest             PASSED in 6.3s
//heron/scheduler-core/tests/java:SchedulerMainTest                      PASSED in 25.4s
//heron/scheduler-core/tests/java:SchedulerServerTest                    PASSED in 2.7s
//heron/scheduler-core/tests/java:SchedulerUtilsTest                     PASSED in 5.9s
//heron/scheduler-core/tests/java:SubmitDryRunRenderTest                 PASSED in 7.2s
//heron/scheduler-core/tests/java:SubmitterMainTest                      PASSED in 5.8s
//heron/scheduler-core/tests/java:UpdateDryRunRenderTest                 PASSED in 8.5s
//heron/scheduler-core/tests/java:UpdateTopologyManagerTest              PASSED in 18.6s
//heron/schedulers/tests/java:AuroraCLIControllerTest                    PASSED in 4.0s
//heron/schedulers/tests/java:AuroraContextTest                          PASSED in 1.6s
//heron/schedulers/tests/java:AuroraLauncherTest                         PASSED in 4.8s
//heron/schedulers/tests/java:AuroraSchedulerTest                        PASSED in 24.3s
//heron/schedulers/tests/java:HeronExecutorTaskTest                      PASSED in 10.1s
//heron/schedulers/tests/java:HeronMasterDriverTest                      PASSED in 16.0s
//heron/schedulers/tests/java:KubernetesControllerTest                   PASSED in 1.6s
//heron/schedulers/tests/java:KubernetesLauncherTest                     PASSED in 4.7s
//heron/schedulers/tests/java:KubernetesSchedulerTest                    PASSED in 4.3s
//heron/schedulers/tests/java:LaunchableTaskTest                         PASSED in 4.5s
//heron/schedulers/tests/java:LocalLauncherTest                          PASSED in 10.7s
//heron/schedulers/tests/java:LocalSchedulerTest                         PASSED in 4.4s
//heron/schedulers/tests/java:MarathonControllerTest                     PASSED in 5.7s
//heron/schedulers/tests/java:MarathonLauncherTest                       PASSED in 4.8s
//heron/schedulers/tests/java:MarathonSchedulerTest                      PASSED in 2.5s
//heron/schedulers/tests/java:MesosFrameworkTest                         PASSED in 3.8s
//heron/schedulers/tests/java:MesosLauncherTest                          PASSED in 2.7s
//heron/schedulers/tests/java:MesosSchedulerTest                         PASSED in 3.5s
//heron/schedulers/tests/java:NomadSchedulerTest                         PASSED in 9.3s
//heron/schedulers/tests/java:SlurmControllerTest                        PASSED in 7.3s
//heron/schedulers/tests/java:SlurmLauncherTest                          PASSED in 5.0s
//heron/schedulers/tests/java:SlurmSchedulerTest                         PASSED in 5.8s
//heron/schedulers/tests/java:TaskResourcesTest                          PASSED in 2.5s
//heron/schedulers/tests/java:TaskUtilsTest                              PASSED in 1.6s
//heron/schedulers/tests/java:VolumesTests                               PASSED in 1.5s
//heron/schedulers/tests/java:YarnLauncherTest                           PASSED in 2.8s
//heron/schedulers/tests/java:YarnSchedulerTest                          PASSED in 2.6s
//heron/simulator/tests/java:AllGroupingTest                             PASSED in 2.4s
//heron/simulator/tests/java:CustomGroupingTest                          PASSED in 2.0s
//heron/simulator/tests/java:FieldsGroupingTest                          PASSED in 2.6s
//heron/simulator/tests/java:InstanceExecutorTest                        PASSED in 2.2s
//heron/simulator/tests/java:LowestGroupingTest                          PASSED in 1.5s
//heron/simulator/tests/java:RotatingMapTest                             PASSED in 2.0s
//heron/simulator/tests/java:ShuffleGroupingTest                         PASSED in 1.6s
//heron/simulator/tests/java:SimulatorTest                               PASSED in 2.0s
//heron/simulator/tests/java:TopologyManagerTest                         PASSED in 2.1s
//heron/simulator/tests/java:TupleCacheTest                              PASSED in 2.1s
//heron/simulator/tests/java:XORManagerTest                              PASSED in 2.8s
//heron/spi/tests/java:ConfigLoaderTest                                  PASSED in 5.8s
//heron/spi/tests/java:ConfigTest                                        PASSED in 4.6s
//heron/spi/tests/java:ContextTest                                       PASSED in 1.5s
//heron/spi/tests/java:ExceptionInfoTest                                 PASSED in 1.6s
//heron/spi/tests/java:KeysTest                                          PASSED in 1.6s
//heron/spi/tests/java:MetricsInfoTest                                   PASSED in 1.3s
//heron/spi/tests/java:MetricsRecordTest                                 PASSED in 1.1s
//heron/spi/tests/java:NetworkUtilsTest                                  PASSED in 6.0s
//heron/spi/tests/java:PackingPlanTest                                   PASSED in 1.6s
//heron/spi/tests/java:ResourceTest                                      PASSED in 2.3s
//heron/spi/tests/java:ShellUtilsTest                                    PASSED in 5.6s
//heron/spi/tests/java:TokenSubTest                                      PASSED in 1.9s
//heron/spi/tests/java:UploaderUtilsTest                                 PASSED in 3.6s
//heron/statefulstorages/tests/java:DlogStorageTest                      PASSED in 10.4s
//heron/statefulstorages/tests/java:HDFSStorageTest                      PASSED in 7.1s
//heron/statefulstorages/tests/java:LocalFileSystemStorageTest           PASSED in 7.1s
//heron/statemgrs/tests/cpp:zk-statemgr_unittest                         PASSED in 0.1s
//heron/statemgrs/tests/java:CuratorStateManagerTest                     PASSED in 2.5s
//heron/statemgrs/tests/java:LocalFileSystemStateManagerTest             PASSED in 4.8s
//heron/statemgrs/tests/java:ZkUtilsTest                                 PASSED in 6.6s
//heron/statemgrs/tests/python:configloader_unittest                     PASSED in 2.7s
//heron/statemgrs/tests/python:statemanagerfactory_unittest              PASSED in 2.8s
//heron/statemgrs/tests/python:zkstatemanager_unittest                   PASSED in 2.5s
//heron/stmgr/tests/cpp/grouping:all-grouping_unittest                   PASSED in 0.2s
//heron/stmgr/tests/cpp/grouping:custom-grouping_unittest                PASSED in 0.1s
//heron/stmgr/tests/cpp/grouping:fields-grouping_unittest                PASSED in 0.2s
//heron/stmgr/tests/cpp/grouping:lowest-grouping_unittest                PASSED in 0.2s
//heron/stmgr/tests/cpp/grouping:shuffle-grouping_unittest               PASSED in 0.3s
//heron/stmgr/tests/cpp/server:checkpoint-gateway_unittest               PASSED in 4.0s
//heron/stmgr/tests/cpp/server:stateful-restorer_unittest                PASSED in 0.4s
//heron/stmgr/tests/cpp/server:stmgr_unittest                            PASSED in 39.8s
//heron/stmgr/tests/cpp/util:neighbour_calculator_unittest               PASSED in 0.1s
//heron/stmgr/tests/cpp/util:rotating-map_unittest                       PASSED in 0.3s
//heron/stmgr/tests/cpp/util:tuple-cache_unittest                        PASSED in 3.8s
//heron/stmgr/tests/cpp/util:xor-manager_unittest                        PASSED in 4.2s
//heron/tmaster/tests/cpp/server:stateful_checkpointer_unittest          PASSED in 0.3s
//heron/tmaster/tests/cpp/server:stateful_restorer_unittest              PASSED in 5.3s
//heron/tmaster/tests/cpp/server:tcontroller_unittest                    PASSED in 0.2s
//heron/tmaster/tests/cpp/server:tmaster_unittest                        PASSED in 38.3s
//heron/tools/apiserver/tests/java:ConfigUtilsTests                      PASSED in 2.1s
//heron/tools/apiserver/tests/java:TopologyResourceTests                 PASSED in 4.0s
//heron/tools/cli/tests/python:client_command_unittest                   PASSED in 2.7s
//heron/tools/cli/tests/python:opts_unittest                             PASSED in 1.6s
//heron/tools/explorer/tests/python:explorer_unittest                    PASSED in 3.6s
//heron/tools/tracker/tests/python:query_operator_unittest               PASSED in 3.0s
//heron/tools/tracker/tests/python:query_unittest                        PASSED in 2.6s
//heron/tools/tracker/tests/python:topology_unittest                     PASSED in 2.2s
//heron/tools/tracker/tests/python:tracker_unittest                      PASSED in 3.8s
//heron/uploaders/tests/java:DlogUploaderTest                            PASSED in 2.1s
//heron/uploaders/tests/java:GcsUploaderTests                            PASSED in 3.0s
//heron/uploaders/tests/java:HdfsUploaderTest                            PASSED in 3.0s
//heron/uploaders/tests/java:HttpUploaderTest                            PASSED in 4.3s
//heron/uploaders/tests/java:LocalFileSystemConfigTest                   PASSED in 1.2s
//heron/uploaders/tests/java:LocalFileSystemContextTest                  PASSED in 1.3s
//heron/uploaders/tests/java:LocalFileSystemUploaderTest                 PASSED in 1.5s
//heron/uploaders/tests/java:S3UploaderTest                              PASSED in 5.1s
//heron/uploaders/tests/java:ScpUploaderTest                             PASSED in 2.9s
```

**Comment by joshfischer1108** [comment]
@nicknezis @thinker0 The travis build file still specifies Java8. I would think that this needs to be updated to java11 before we can merge. https://github.com/thinker0/heron/blob/bc7d038495c59da76738864eb077adedbd5a166d/.travis.yml#L10

**Comment by thinker0** [comment]
@joshfischer1108 Binaries made with jdk11 do not work with jdk8. The binary created with jdk8 above works with both jdk8 and jdk11, so I think that it should be jdk8 now.

**Comment by joshfischer1108** [comment]
Ok makes sense to me

**Comment by nwangtw** [comment]
Some unit tests are failing on Travis. The travis config (heron/.travis.yml) isnot updated?

**Comment by nwangtw** [comment]
Hmm. It is jdk 11 in .travis.yml. Here are the failures:

(16:20:00) INFO: Build completed, 2 tests FAILED, 1558 total actions
//heron/scheduler-core/tests/java:RuntimeManagerMainTest                 FAILED in 9.2s
    FAILED  org.apache.heron.scheduler.RuntimeManagerMainTest.testManageTopologyNoClass (0.4s)
//heron/scheduler-core/tests/java:SubmitterMainTest                      FAILED in 4.5s
    FAILED  org.apache.heron.scheduler.SubmitterMainTest.testSubmitTopologyClassNotExist (0.1s)
Test cases: finished with 1133 passing and 2 failing out of 1135 test cases

But only 2 failures!! Great work!

**Comment by thinker0** [comment]
```
--add-opens=java.base/java.lang=ALL-UNNAMED
```
should have permission.

**Comment by thinker0** [comment]
@joshfischer1108 @nwangtw ^_____________^

**Comment by joshfischer1108** [comment]
@thinker0  Thank you for this contribution and job well done sir.  Code and Docker changes look great.  I'm going to let this sit for little while longer to let others review.  You got my 👍

**Comment by nicknezis** [comment]
I think it looks good. I do think we should have both Travis and the Dockerfiles set to JDK 11. I don't see a reason to keep Travis or Dockerfiles set to JDK 8. Is this too short sighted? Thoughts? What does Jenkins build use? If Heron team produces official jars, what version of Java would that target?

**Comment by joshfischer1108** [comment]
@nicknezis Travis and Dockerfiles are set to jdk 11 from what I can see.

**Comment by thinker0** [comment]
> Ok makes sense to me

What you want is
travis.yml should be jdk11 ?,
Should Docker be jdk8/jdk11 ?

**Comment by thinker0** [comment]
I use it in mesos/aurora, so I think I should go to jdk11 because jdk11 supports CGROUP Container well. jkd8 is not suitable for container.

**Comment by joshfischer1108** [comment]
@thinker0 I think this PR looks good to me as is.  It looks to me as though you have changed the travis file and several docker files (if not all of them) to use jdk11.  If there are any other missing Dockerfile entries we can get them after this PR is merged.  Really nice work.

**Comment by nwangtw** [comment]
Again, great work!

There might be some more update. But let me merge this PR first. It has been in progress for almost 4 months since the work started.

**Pull request merged**
