### PR TITLE
Switch to pigz to support multi-core tar command

### PR DESCRIPTION
**Pull request by windhamwong**
pigz is a multi-core version of tar, which makes the docker build process much faster.

### CODE REVIEW

**Comment by nicknezis** [comment]
I'm not familiar with `pigz`. Is the resulting artifact equivalent to a gzip artifact? Does a user need `pigz` installed to `tar -xzf` the resulting files? Does that command even still work?

**Comment by Code0x58** [comment]
A couple of tests to show equivalence for consumers:
With gzip:
```
$ cat txt 
oink
$ ls
txt
$ pigz txt
$ ls
txt.gz
$ gunzip txt.gz 
$ ls
txt
$ cat txt 
oink
```
With tar:
```
$ tar --remove-files --use-compress-program=pigz -cf out.tar.gz txt
$ ls
out.tar.gz
$ tar -zxf out.tar.gz
$ cat txt
oink
```

**Comment by windhamwong** [comment]
https://zlib.net/pigz/
It is gzip format but with the parallel multi-core feature. The traditional gzip command uses only one core but modern CPU/vCPU has more than one.

**Comment by nicknezis** [comment]
1. Have all containers been tested? Do some of them need `pigz` included in their Dockerfiles?
2. Should `bazel_configure.py` be updated to check for `pigz` if it is an external dependency?
3. Do any of the website pages need to be updated? For instance `brew install pigz` for someone compiling on their Mac.

**Comment by windhamwong** [comment]
let me try out all docker builds tomorrow.

**Comment by windhamwong** [comment]
Docker build testing result:
ubuntu18.04 - success
ubuntu20.04 - success
ubuntu16.04 - success
debian9 - fail - python3.6 not supported (unrelated to pigz)
debian10 - fail - protobuf issue (unrelated to pigz)
centos7 - success

**Pull request merged**
