### PR TITLE
merge rename from com.twitter to org.apache [apache#2828]

### PR DESCRIPTION
**Pull request by sreev**
rename folders
rename imports
update script links
update doc links

### CODE REVIEW

**Comment by sreev** [comment]
> (06:17:20) ERROR: /home/travis/build/apache/incubator-heron/heron/statemgrs/src/java/BUILD:82:1: Executing extra_action //tools/java:checkstyle_java on //heron/statemgrs/src/java:zookeeper-statemgr-unshaded failed (Exit 2): bash failed: error executing command 
>   (cd /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron && \
>   exec env - \
>     PATH=/usr/bin:/opt/pyenv/libexec:/opt/pyenv/plugins/python-build/bin:/usr/lib/jvm/java-8-oracle/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.7/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin \
>   /bin/bash -c 'bazel-out/host/bin/tools/java/src/org/apache/bazel/checkstyle/checkstyle_java --extra_action_file bazel-out/k8-fastbuild/extra_actions/tools/java/checkstyle_java/heron/statemgrs/src/java/91e041116f510e1abfa9263b60052f0b.xa --heron_checkstyle_config_file tools/java/src/org/apache/bazel/checkstyle/heron_coding_style.xml --apache_checkstyle_config_file tools/java/src/org/apache/bazel/checkstyle/apache_coding_style.xml')
> Starting audit...
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/statemgrs/src/java/org/apache/heron/statemgr/zookeeper/ZkWatcherCallback.java:20: Wrong order for 'org.apache.heron.spi.statemgr.WatchCallback' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/statemgrs/src/java/org/apache/heron/statemgr/zookeeper/curator/CuratorStateManager.java:41: Wrong order for 'org.apache.heron.api.generated.TopologyAPI' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> Audit done.
> Checkstyle ends with 2 errors.

**Comment by sreev** [comment]
> (08:08:08) ERROR: /home/travis/build/apache/incubator-heron/heron/uploaders/tests/java/BUILD:58:1: Executing extra_action //tools/java:checkstyle_java on //heron/uploaders/tests/java:DlogUploaderTest failed (Exit 1): bash failed: error executing command 
>   (cd /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron && \
>   exec env - \
>     PATH=/usr/bin:/opt/pyenv/libexec:/opt/pyenv/plugins/python-build/bin:/usr/lib/jvm/java-8-oracle/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.7/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin \
>   /bin/bash -c 'bazel-out/host/bin/tools/java/src/org/apache/bazel/checkstyle/checkstyle_java --extra_action_file bazel-out/k8-fastbuild/extra_actions/tools/java/checkstyle_java/heron/uploaders/tests/java/eff0462a84339f65c80ebc1ef599c9b6.xa --heron_checkstyle_config_file tools/java/src/org/apache/bazel/checkstyle/heron_coding_style.xml --apache_checkstyle_config_file tools/java/src/org/apache/bazel/checkstyle/apache_coding_style.xml')
> Starting audit...
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/uploaders/tests/java/org/apache/heron/uploader/dlog/DlogUploaderTest.java:25: Wrong order for 'org.junit.Before' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> Audit done.
> Checkstyle ends with 1 errors.
>

**Comment by sreev** [comment]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/uploaders/tests/java/org/apache/heron/uploader/dlog/DlogUploaderTest.java:28: Wrong order for 'org.junit.Before' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/uploaders/tests/java/org/apache/heron/uploader/dlog/DlogUploaderTest.java:36: Using the '.*' form of import should be avoided - org.mockito.Mockito.*. [AvoidStarImport]
> Audit done.
> Checkstyle ends with 2 errors.
> (08:38:29) INFO: Elapsed time: 1205.889s, Critical Path: 425.19s
> (08:38:29) FAILED: Build did NOT complete successfully

**Comment by sreev** [comment]
> Making install in doc
> make[1]: Entering directory `/home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/tmp244_1e818feb61dcc793/libunwind.oQ5wx/doc'
> latex2man -t ./libunwind.trans unw_get_accessors.tex unw_get_accessors.man
> make[1]: Leaving directory `/home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/tmp244_1e818feb61dcc793/libunwind.oQ5wx/doc'
> ptrace/_UPT_get_dyn_info_list_addr.c: In function 'get_list_addr':
> ptrace/_UPT_get_dyn_info_list_addr.c:78:3: warning: #warning Implement get_list_addr(), please. [-Wcpp]
>  # warning Implement get_list_addr(), please.
>    ^
> coredump/_UPT_get_dyn_info_list_addr.c: In function 'get_list_addr':
> coredump/_UPT_get_dyn_info_list_addr.c:81:3: warning: #warning Implement get_list_addr(), please. [-Wcpp]
>  # warning Implement get_list_addr(), please.
>    ^
> /bin/bash: latex2man: command not found
> make[1]: *** [unw_get_accessors.man] Error 127
> make: *** [install-recursive] Error 1
> (18:33:55) INFO: Elapsed time: 48.979s, Critical Path: 20.68s
> (18:33:55) FAILED: Build did NOT complete successfully
> 
> 
> 
> (22:13:51) ERROR: /home/travis/build/apache/incubator-heron/heron/schedulers/src/java/BUILD:164:1: Executing extra_action //tools/java:checkstyle_java on //heron/schedulers/src/java:yarn-scheduler-unshaded failed (Exit 5): bash failed: error executing command 
>   (cd /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron && \
>   exec env - \
>     PATH=/usr/bin:/opt/pyenv/libexec:/opt/pyenv/plugins/python-build/bin:/usr/lib/jvm/java-8-oracle/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.9.1/bin:/home/travis/.kiex/elixirs/elixir-1.4.5/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/phantomjs/bin:/usr/local/phantomjs:/usr/local/neo4j-3.2.7/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin \
>   /bin/bash -c 'bazel-out/host/bin/tools/java/src/org/apache/bazel/checkstyle/checkstyle_java --extra_action_file bazel-out/k8-fastbuild/extra_actions/tools/java/checkstyle_java/heron/schedulers/src/java/cf5cd75c3c2d02b81710a6837bdac016.xa --heron_checkstyle_config_file tools/java/src/org/apache/bazel/checkstyle/heron_coding_style.xml --apache_checkstyle_config_file tools/java/src/org/apache/bazel/checkstyle/apache_coding_style.xml')
> Starting audit...
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/schedulers/src/java/org/apache/heron/scheduler/yarn/HeronDriverConfiguration.java:24: Wrong order for 'org.apache.heron.scheduler.yarn.HeronConfigurationOptions.Cluster' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/schedulers/src/java/org/apache/heron/scheduler/yarn/HeronExecutorTask.java:33: Wrong order for 'org.apache.heron.api.exception.InvalidTopologyException' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/schedulers/src/java/org/apache/heron/scheduler/yarn/HeronMasterDriver.java:56: Wrong order for 'org.apache.heron.api.exception.InvalidTopologyException' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/schedulers/src/java/org/apache/heron/scheduler/yarn/HeronTaskConfiguration.java:23: Wrong order for 'org.apache.heron.scheduler.yarn.HeronConfigurationOptions.Cluster' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> [ERROR] /home/travis/.cache/bazel/_bazel_travis/be6dac4936703c7eedcb4f5cf38cdd65/execroot/org_apache_heron/heron/schedulers/src/java/org/apache/heron/scheduler/yarn/YarnLauncher.java:37: Wrong order for 'org.apache.heron.scheduler.yarn.HeronMasterDriver.ContainerAllocationHandler' import. Order should be: java, javax, scala, com, net, org, org.apache. Each group should be separated by a single blank line. Static imports at the bottom. [ImportOrder]
> Audit done.
> Checkstyle ends with 5 errors.
> (22:13:51) INFO: Elapsed time: 1304.852s, Critical Path: 361.65s
> (22:13:51) FAILED: Build did NOT complete successfully
>

**Comment by ashvina** [comment]
Also, I think it will be worthwhile sharing the tests executed to verify the change. In this case I believe unit tests and integration tests may not be sufficient. I am thinking of verifying heron on YARN cluster. What do you think about this?

**Comment by kramasamy** [comment]
It might be easier if you could help test in yarn cluster - since we don't have access to it at streamlio. Just running the integration tests will help.

**Comment by sreev** [comment]
redoing the rename from the beginning.

**Comment by nwangtw** [comment]
After merging, I will do some tests as well in aurora environment.

**Comment by sreev** [comment]
i am closing this PR, now and will reopen a brand new, later, soon.

**Pull request closed without merging**
