### PR TITLE
Add a spouts directory and README for spout implementations

### PR DESCRIPTION
**Pull request by nwangtw**
Heron community has been interested in maintaining spout implementations for users. There have been discussions in slack channel (#general) and dev@ mailing list.

There are multiple options and each has its own pros and cons. This PR is just a start of the effort to unblock contributors. The directory might be migrated to a different place after a final decision is made.

Please feel free to comment or join the discussion in dev@heron.apache.org.

### CODE REVIEW

**Comment by huijunw** [comment]
there was a contrib dir, which included spouts.
https://github.com/apache/incubator-heron/tree/0.15.0/contrib
i think we may recover the contrib dir, and incubate codes such as spouts from there till they are migrated to other places. thoughts?

**Comment by nwangtw** [comment]
> there was a contrib dir, which included spouts.
> https://github.com/apache/incubator-heron/tree/0.15.0/contrib
> i think we may recover the contrib dir, and incubate codes such as spouts from there till they are migrated to other places. thoughts?

Cool. Thanks!

**Comment by nwangtw** [comment]
I am thinking maybe we should have both spouts and bolts. Both are for reusable components anyway. For example KafkaSpout reads from Kafka and KafkaBolt could be the writer.

**Comment by simingweng** [comment]
@nwangtw definitely make sense to have both Spout and Bolt, Apache Storm has the same thing.

**Comment by nwangtw** [comment]
@simingweng thx for the input!

**Pull request merged**
