### PR TITLE
Add component config in heron UI and Tracker

### PR DESCRIPTION
**Pull request by nwangtw**
Output:

Property | Value
-- | --
topology.message.timeout.secs | 30
topology.fall.back.on.java.serialization | valuenil 
topology.serializer.classname | org.apache.storm.serialization.HeronPluggableSerializerDelegate
topology.worker.childopts | -XX:+HeapDumpOnOutOfMemoryError
topology.workers | 2
topology.kryo.factory | org.apache.storm.serialization.DefaultKryoFactory
topology.debug | true
topology.max.spout.pending | 1000000000
topology.acker.executors | 1
topology.enable.message.timeouts | true
topology.component.parallelism | 1
topology.name | AckingTopology
topology.skip.missing.kryo.registrations | valuenil 
topology.stmgrs | 2
topology.reliability.mode | ATLEAST_ONCE
[word] topology.component.parallelism | 2
[exclaim1] topology.component.parallelism | 2

### CODE REVIEW

**Comment by cckellogg** [comment]
Will this break the explorer?

**Comment by nwangtw** [comment]
@cckellogg shouldn't be. the new data is an extra field in the physical plan json output.

We don't use this tool internal. Let me see how to test.

**Comment by kramasamy** [comment]
@nwangtw - is this ready to be merged?

**Comment by nwangtw** [comment]
Sorry I haven't got chance to test it yet.

**Comment by nwangtw** [comment]
Verified that explore works ok with the change.

**Comment by nwangtw** [comment]
So quick. Thanks. :)

**Pull request merged**
