### PR TITLE
Helm: Adding option to switch the apiserver service between NodePort and ClusterIP

### PR DESCRIPTION
**Pull request by windhamwong**
It gives an option for users to pick whether the apiserver service should be NodePort or ClusterIP.

### CODE REVIEW

**Comment by nicknezis** [comment]
> > Is there a way to support asking for NodePort and letting k8s pick a random port, while also allowing for explicit port selection in the value.yml? Perhaps a property to enable/disable and another to set the value?
> 
> good idea, maybe
> 
> ```
> apiserver:
>   NodePort:
>     enabled: true
>     port: <leave empty for random>
> ```

Yeah I think that could work.

**Comment by windhamwong** [comment]
@nicknezis have a look :D

**Comment by nicknezis** [comment]
Going to do some testing and maybe add the ability to use a random port number. Also just noticed that this feature branch is not made off of the main branch. We should rebase so that it can merge without any of the ARM branch's dependencies.

**Comment by nicknezis** [comment]
@windhamwong I made the branch off of `master` branch. 

I also realized that `helm` was stripping away the comments in the generated `values.yml` file. This issue was documented [here](https://github.com/helm/helm/issues/6951). It's fixed in Helm 3.1.0, so I updated the version of Helm that we are using.

I also did some minor refactoring of the values to start aggregating `apiserver`, `tracker` and `ui` sets of properties.

I also moved the `apiserver` Service up in `tools.yml` to group it with the other two `Service` definitions.

I also mirrored your logic to add `NodePort` support to the other two services.

I chose to keep the default behavior with k8s auto picking the NodePort.

**Review by nicknezis — APPROVED** [review]

**Comment by windhamwong** [comment]
The pushed code looks alright to me.

**Pull request merged**
