### PR TITLE
Update physical-plan.js

### PR DESCRIPTION
**Pull request by windhamwong**
Fixing the JS issue on heron-ui

### CODE REVIEW

**Comment by windhamwong** [comment]
#3801

**Comment by surahman** [comment]
I think this is one of the issues @nicknezis is tackling in #3786. If you have experience with debugging the Heron UI please have a look at that PR when you have time.

**Comment by nicknezis** [comment]
Yes, this is part of a larger set of issues being fixed in #3786. I'll try to wrap it up shortly. Would love some help reviewing my changes on that PR. I ended up changing the Heron Tracker API and I can see an argument towards not doing what I did. I'm going to close this PR. @windhamwong We can work together on the PR I started.

**Comment by surahman** [comment]
I would like help with #3786 but I am having issues getting data into the UI and do not have the time right now to debug that specific issue. I can bring up the UI but there is no data inflow from the tracker.

**Pull request closed without merging**
