### PR TITLE
[DO NOT MERGE] - K8S Conversion to using Replica Sets

### PR DESCRIPTION
**Pull request by jrcrawfo**
What?
Changes to the k8s scheduler to use replica sets as the mechanism for deployment of topology containers

Why?
Using pods (previous version) wasn't fault tolerant when k8s nodes would fail.

### CODE REVIEW

**Comment by jrcrawfo** [comment]
Still a work in progress as there is a bug in the update function -- not quite sure of the source of the bug, as it's not related to the scheduler. This bug is preventing me from testing the update functionality, however.

**Comment by srkukarni** [comment]
@jrcrawfo What is the symptoms of the bug? Does it exist in master as well?

**Comment by jrcrawfo** [comment]
@srkukarni i can look against master later, but here's the exception i was getting:

```
com.twitter.heron.spi.packing.PackingException: Could not initialize containers using existing packing plan
        at com.twitter.heron.packing.builder.PackingPlanBuilder.initContainers(PackingPlanBuilder.java:259)
        at com.twitter.heron.packing.builder.PackingPlanBuilder.addInstance(PackingPlanBuilder.java:153)
        at com.twitter.heron.packing.builder.PackingPlanBuilder.addInstance(PackingPlanBuilder.java:141)
        at com.twitter.heron.packing.binpacking.FirstFitDecreasingPacking.placeFFDInstance(FirstFitDecreasingPacking.java:312)
        at com.twitter.heron.packing.binpacking.FirstFitDecreasingPacking.assignInstancesToContainers(FirstFitDecreasingPacking.java:265)
        at com.twitter.heron.packing.binpacking.FirstFitDecreasingPacking.getFFDAllocation(FirstFitDecreasingPacking.java:246)
        at com.twitter.heron.packing.binpacking.FirstFitDecreasingPacking.repack(FirstFitDecreasingPacking.java:180)
        at com.twitter.heron.scheduler.RuntimeManagerRunner.buildNewPackingPlan(RuntimeManagerRunner.java:303)
        at com.twitter.heron.scheduler.RuntimeManagerRunner.updateTopologyHandler(RuntimeManagerRunner.java:182)
        at com.twitter.heron.scheduler.RuntimeManagerRunner.call(RuntimeManagerRunner.java:81)
        at com.twitter.heron.scheduler.RuntimeManagerMain.callRuntimeManagerRunner(RuntimeManagerMain.java:448)
        at com.twitter.heron.scheduler.RuntimeManagerMain.manageTopology(RuntimeManagerMain.java:396)
        at com.twitter.heron.scheduler.RuntimeManagerMain.main(RuntimeManagerMain.java:317)
Caused by: com.twitter.heron.packing.ResourceExceededException: Insufficient container resources to add instancePlan {component-name: exclaim1, task-id: 4, component-index: 3, instance-resource: {cpu: 1.000000, ram: ByteAmount{256 MB (268435456 bytes)}, disk: ByteAmount{1 GB (1073741824 bytes)}}} to container {containerId=2, instances=[{component-name: exclaim1, task-id: 2, component-index: 1, instance-resource: {cpu: 1.000000, ram: ByteAmount{256 MB (268435456 bytes)}, disk: ByteAmount{1 GB (1073741824 bytes)}}}], capacity={cpu: 1.000000, ram: ByteAmount{3 GB (2952790016 bytes)}, disk: ByteAmount{3 GB (3221225472 bytes)}}, paddingPercentage=10}[2017-10-18 09:49:32 -0400] [ERROR]: Could not initialize containers using existing packing plan

        at com.twitter.heron.packing.builder.PackingPlanBuilder.getContainers(PackingPlanBuilder.java:392)
[2017-10-18 09:49:32 -0400] [ERROR]: Failed to update topology: exclamationtopology
[2017-10-18 09:49:32 -0400] [DEBUG]: Elapsed time: 8.798s.
```

Was using the `heron.class.repacking.algorithm:  com.twitter.heron.packing.binpacking.FirstFitDecreasingPacking` repacking class

**Comment by srkukarni** [comment]
@cckellogg Might be related to the same issue that you are looking into

**Comment by cckellogg** [comment]
This is different. The issue I was seeing earlier was with the RoundRobinPackingPlan. It would be helpful to have a better to have more meaningful error message.

**Comment by cckellogg** [comment]
What about using stateful sets instead? We would only have to make one rest call to start the topology then. Also, pods will have a predictable name too. The trick is to find the ordinal for the pod and then we can use that as the shard?

**Comment by jrcrawfo** [comment]
@cckellogg i personally wouldn’t recommend using a stateful set, as it’s beta in the newest version (1.8 not available on google compute engine yet either). I'm also not sure you'd be able to get away with making one rest call, as every heron instance (pod) has a different command line argument. Keep in mind the specs that work for `kubectl` commands don't necessarily translate to API commands as well. `kubectl` does a lot of work itself making multiple API calls to get things deployed even it is just one command using `kubectl`

**Comment by cckellogg** [comment]
We have been using stateful sets for zookeeper for a while so I'm not concerned with the beta part. Also, replicasets are in beta too. What i like about the stateful sets is that it groups everything together (with replica sets we would have to create one for each container/pod) and they provides a predictable name for the pod. The only thing that changes in the heron command currently is the shard-id right?
Stateful sets will give each pod an ordinal and if one of those pods does down it will restart with the same ordinal. 
Thoughts?

**Comment by cckellogg** [comment]
@jrcrawfo is this patch ready with the replica sets?

**Comment by nicknezis** [comment]
Closing this merge request because Heron is now using Kubernetes StatefulSets

**Pull request closed without merging**
