### PR TITLE
Python 3 upgrade

### PR DESCRIPTION
**Pull request by Code0x58**
This upgrades to Python 3.6+ A summary from the commit messages:
 * update heronpy release scripts for python3-only release
 * update Dockerfiles to only use python3 (includes fixes to unbuildable images)
 * fix pylint: upgrade to latest + clean up new lint issues were fixed along the way
 * fix transitive dependencies not being captured in PEXs: upgrade PEX tool to latest
 * (1) patch PEX imports of pex_library not working: use pex with --zip-safe=false
 * (2) patch python proto_library: rewrite relative imports
 * (3) update cloudpickle code
 * update vagrant environment to Ubuntu 20.04 and add `./vagrant/local-ci.sh` which runs CI matching Travis. It gives a fair chunk of resources to the VM and is tested on Mac + Linux, and makes debugging easier. Mesos/Aurora was dropped just to make the upgrade easier, with the assumption someone can update that if it's still supported

Issues that follow on from this:
 1. using zip-safe=False was a workaround for imports not working. More investigation needed
 2. use long term solution for patch in `tools/rules/genproto.bzl` which is from https://github.com/protocolbuffers/protobuf/issues/1491, possibly one of:
    - using standard protobuf bazel rules and their `import_prefix`
    - use relative paths in the protoc command so the imports are absolute (mentioned in issue)
    - pursue https://github.com/protocolbuffers/protobuf/pull/7470
 3. look at unvendoring cloudpickle and using a package from pypi
 4. pkg_tar requires a `python` in the environment, so something like `python2` or `python-is-python3` has to be installed in build environments (e.g. `docker/compile/Dockerfile.*`). `pkg_tar` rules have been deprecated in core bazel and made external

areas to check/known risks:
 *  / acted as // when both parts were ints, but now it always converts to a float - some places caught this change in tests (i.e. Metrics)
 * ordering in dicts has changed since python 3.6 - it appears cases of this were caught in executor tests
 * bytes vs str - paths with test coverage had this fixed
 * test coverage - some components may not be tested in CI, for example ZK state managers or non-local schedulers

Things noticed along the way for future clean up issues:
 * `enum34`, `mock`, and `unittest2` can be replaced with python3  built in libraries - these can be listed with `bazel query 'attr('reqs', "(unittest|enum34|mock)", kind("pex_library", //heron/...))'
//heron/tools/admin/src/python:admin-py`
* [`buildifier`](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md) could be added to the scripts+tests (it can be acquired via `http_file(...)`) - turns out it's not that easy/nice because `select(...)` can't be used at the top level WORKSPACE
 * travis is taking nearly 3 hours and isn't necessarily a single pipeline, so could be broken up into slightly overlapping but concurrent parts (e.g. `./scripts/travis/build.sh` and `./scripts/travis/test.sh`) to cut down wall clock build times from what is nearly 3 hours at the moment (with some fail-fast that, but that may not be an issue). This would be a great place to have a separate lint stage to expose all issues in one go
 * it looks like there are several definitions of things like builds/releases from all the different scripts in `scripts/...` - I suspect they could use some consolidation and cleaning up
 * `docker/{compile,dist,base,test}/*` look like good candidates for consolidation with [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/)

tidbits and trivia:
* overview of `pex_library.reqs`: `bazel query 'attr('reqs', ".{3,}", kind("pex_library", //heron/...))' --output=build | grep reqs | cut -d \[ -f2 | sed 's/\],//' | sed 's/, /\n/g' | sort | uniq -c`
* [`unused_deps`](https://github.com/bazelbuild/buildtools/blob/master/unused_deps/README.md) isn't safe to use on the codebase at the moment, but could be something to look into
* upgrading pylint may have been a lot less painful if all of the linting was done in one go

### CODE REVIEW

**Comment by joshfischer1108** [comment]
I did a local test on OSX by creating the install scripts.  So far it did not work as expected. I do think we are very close.  I installed Heron by the following:

**Note:** All commands are ran from the root directory of the project
```
$ bazel build --config=darwin_nostyle scripts/packages:binpkgs
````
The above command's output is the install scripts. The location of the scripts will be echoed to the terminal.  Typically something like:
```
 Target //scripts/packages:binpkgs up-to-date:
  bazel-bin/scripts/packages/heron-install.sh
```
   I then installed them.
```
$ ./bazel-bin/scripts/packages/heron-install.sh --user
```
I checked the heron version command.  All good.
```
$  heron version
heron.build.git.revision : 1f80d5a20fbd146597de7dab3c94816a602239fd
heron.build.git.status : Clean
heron.build.host : Joshs-MacBook-Pro-2.local
heron.build.time : Fri May 29 21:11:31 CDT 2020
heron.build.timestamp : 1590804691000
heron.build.user : joshfischer
heron.build.version : python-3-upgrade
```
Then I started the tracker.  All good.
```
$ heron-tracker
[2020-05-29 21:42:22 -0500] [INFO]: Connecting to file state with rootpath: /Users/joshfischer/.herondata/repository/state/local
[2020-05-29 21:42:22 -0500] [INFO]: Tracker has started
[2020-05-29 21:42:22 -0500] [INFO]: Running on port: 8888
[2020-05-29 21:42:22 -0500] [INFO]: Using config file: /Users/joshfischer/.heron/conf/heron_tracker.yaml
[2020-05-29 21:42:22 -0500] [INFO]: Using state manager:
	type: file
	name: local
	rootpath: ~/.herondata/repository/state/local
	tunnelhost: 127.0.0.1
```

When trying to start the UI piece of Heron it looks like it could not find the `release.yaml` file.  See below:
```
$ heron-ui
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 396, in execute
  File ".bootstrap/pex/pex.py", line 328, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 359, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 447, in _execute
  File ".bootstrap/pex/pex.py", line 544, in execute_entry
  File ".bootstrap/pex/pex.py", line 551, in execute_module
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/joshfischer/.pex/code/6e6aa1266ca563ae910c0bca80d652a68d3e9d94/heron/tools/ui/src/python/main.py", line 40, in <module>
    from heron.tools.ui.src.python import args
  File "/Users/joshfischer/.pex/code/6e6aa1266ca563ae910c0bca80d652a68d3e9d94/heron/tools/ui/src/python/args.py", line 24, in <module>
    import heron.tools.ui.src.python.consts as consts
  File "/Users/joshfischer/.pex/code/6e6aa1266ca563ae910c0bca80d652a68d3e9d94/heron/tools/ui/src/python/consts.py", line 35, in <module>
    VERSION = common_config.get_version_number(zipped_pex=True)
  File "/Users/joshfischer/.pex/code/6e6aa1266ca563ae910c0bca80d652a68d3e9d94/heron/tools/common/src/python/utils/config.py", line 476, in get_version_number
    with open(release_file) as release_info:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/joshfischer/.heron/scripts/packages/release.yaml'
```
However, the `release.yaml` is in the `~/.heron` directory.  Just not in that location.
```
cd ~/.heron/
bin/          dist/         examples/     lib/          
conf/         etc/          include/      release.yaml 
```

I may have to rebuild master and see if it expects the `release.yaml` to be in the same location.  Not sure yet.

**Comment by Code0x58** [comment]
Thanks @joshfischer1108 for checking it out! I pushed 5efa344 to fix that, which at least seems to run without any toplogies (yet to try with). I'm making some basic bests for the helm chart with everything scaled down to one, and can try adding extra steps you do

**Comment by joshfischer1108** [comment]
Thanks @Code0x58 .  I'll do some more checking this weekend.

**Comment by Code0x58** [comment]
I just pushed a change that should get you at least a little further. I'm still working on getting the integration to run against k8s, so will hopefully have some time for that this weekend

**Comment by joshfischer1108** [comment]
@Code0x58 I haven't forgotten about your PR.  I'm trying to wrap up some work I had ahead of this so that we can start a new release candidate vote.   I assumed it would have been done sooner, but I had forgotten about one last task. Once I have that fixed. I'll come back to this.  Hope this is ok.

**Comment by huijunwu** [comment]
Followed the steps in https://github.com/apache/incubator-heron/pull/3522#issuecomment-636266189, the Tracker and UI look good to me. 
My environment: Ubuntu 20.04, Python 3.8.2

**Comment by huijunwu** [comment]
Test with minikue. Looks good

```
$ hostnamectl
         Icon name: computer-desktop
           Chassis: desktop
  Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-40-generic
      Architecture: x86-64
$ docker --version
Docker version 19.03.8, build afacb8b7f0

git clone https://github.com/apache/incubator-heron.git
git remote add Code0x58 https://github.com/Code0x58/incubator-heron.git 
git fetch Code0x58
git checkout --track Code0x58/python-3-upgrade

./docker/scripts/build-artifacts.sh ubuntu20.04 0.0.0 ~/heron-release

$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd

eval $(minikube -p minikube docker-env)
./docker/scripts/build-docker.sh ubuntu20.04 0.0.0 ~/heron-release

# cluster
DIR=./deploy/kubernetes/minikube
sed 's!heron/heron:latest!heron/heron:0.0.0!g' ${DIR}/zookeeper.yaml > /tmp/zookeeper.yaml
sed 's!heron/heron:latest!heron/heron:0.0.0!g' ${DIR}/tools.yaml > /tmp/tools.yaml
sed 's!heron/heron:latest!heron/heron:0.0.0!g' ${DIR}/apiserver.yaml > /tmp/apiserver.yaml

kubectl create -f /tmp/zookeeper.yaml
kubectl get pods
kubectl create -f ${DIR}/bookkeeper.yaml
kubectl create -f /tmp/tools.yaml
kubectl create -f /tmp/apiserver.yaml

# submit a job
kubectl proxy -p 8001 &

curl http://localhost:8001/api/v1/namespaces/default/services/heron-apiserver:9000/proxy/api/v1/version
heron config kubernetes set service_url http://localhost:8001/api/v1/namespaces/default/services/heron-apiserver:9000/proxy
heron submit kubernetes ~/.heron/examples/heron-api-examples.jar org.apache.heron.examples.api.AckingTopology acking
heron kill kubernetes acking

# clean
kubectl delete -f /tmp/zookeeper.yaml
kubectl delete -f ${DIR}/bookkeeper.yaml
kubectl delete -f /tmp/tools.yaml
kubectl delete -f /tmp/apiserver.yaml
```

**Comment by joshfischer1108** [comment]
I'm testing this branch on the `darwin` platform today.

**Comment by joshfischer1108** [comment]
All good on Darwin and Debian10 platforms.  👍 @Code0x58 

```


$ docker --version
Docker version 19.03.8, build afacb8b

git clone https://github.com/apache/incubator-heron.git
git remote add Code0x58 https://github.com/Code0x58/incubator-heron.git 
git fetch Code0x58
git checkout --track Code0x58/python-3-upgrade

# Darwin

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

$ heron submit local  ~/.heron/examples/heron-api-examples.jar org.apache.heron.examples.api.AckingTopology acking

$ heron kill local acking

# Debian10
./docker/scripts/build-artifacts.sh debian10 0.0.0 ~/heron-release

$ docker run -it --rm  -p 8889:8889 heron/heron:0.0.0 bash

#All of the following commands were ran from inside the running container
$ supervisord

$ heron submit sandbox  ./examples/heron-api-examples.jar org.apache.heron.examples.api.AckingTopology acking

$ heron kill sandbox acking
```

**Comment by joshfischer1108** [comment]
@nwangtw / @nlu90 could both of you test this out before we merge?

**Comment by nwangtw** [comment]
> @nwangtw / @nlu90 could both of you test this out before we merge?

ack.

**Comment by huijunwu** [comment]
I think we are ready to merge.

**Pull request merged**
