### PR TITLE
Deep clean heron-explorer

### PR DESCRIPTION
**Pull request by Code0x58**
* use click instead of argparse pattern
 * list all topologies instead of just 20
 * not strictly the same CLI argument names but same functionality
   - still consistent with existing web documentation
   - automatically documented with `--help` flag thanks to click
   - can see examples in the added integration tests
 * add smoke testes for heron-tracker and heron-explorer in local-test-runner

I'm getting the feeling that after cleaning up the rest of the CLIs, it may be good to look at consolidating the explorer functionality into the heron CLI

### CODE REVIEW

**Comment by huijunwu** [comment]
tested on macos, several issues:

1. need to toggle verbose, see below
```
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer logical-plan local hello-world-topology
[2020-07-31 07:32:21 -0700] [DEBUG]: fetching url http://127.0.0.1:8888/topologies/logicalplan?cluster=local&environ=default&topology=hello-world-topology&role=huijunw
[2020-07-31 07:32:21 -0700] [DEBUG]: TIME: url fetch took 0.39 ms server time http://127.0.0.1:8888/topologies/logicalplan?cluster=local&environ=default&topology=hello-world-topology&role=huijunw
[2020-07-31 07:32:21 -0700] [DEBUG]: TIME: url fetch took 29.01 ms round trip  http://127.0.0.1:8888/topologies/logicalplan?cluster=local&environ=default&topology=hello-world-topology&role=huijunw
[2020-07-31 07:32:21 -0700] [DEBUG]: fetching url http://127.0.0.1:8888/topologies/info?cluster=local&environ=default&topology=hello-world-topology&role=huijunw
[2020-07-31 07:32:21 -0700] [DEBUG]: TIME: url fetch took 0.11 ms server time http://127.0.0.1:8888/topologies/info?cluster=local&environ=default&topology=hello-world-topology&role=huijunw
[2020-07-31 07:32:21 -0700] [DEBUG]: TIME: url fetch took 4.45 ms round trip  http://127.0.0.1:8888/topologies/info?cluster=local&environ=default&topology=hello-world-topology&role=huijunw
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer --verbose logical-plan local hello-world-topology
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -

```
2. some options order in the help-info are wrong? 
```
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer topologies --help
Usage: heron-explorer topologies [OPTIONS] CLUSTER[/ROLE[/ENV]]

Options:
  --tracker-url TEXT
  --help              Show this message and exit.

[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer topologies local --tracker-url http://127.0.0.1:8888 
[2020-07-31 07:43:20 -0700] [DEBUG]: fetching url http://127.0.0.1:8888/topologies?cluster=local
[2020-07-31 07:43:20 -0700] [DEBUG]: TIME: url fetch took 0.10 ms server time http://127.0.0.1:8888/topologies?cluster=local
[2020-07-31 07:43:20 -0700] [DEBUG]: TIME: url fetch took 22.43 ms round trip  http://127.0.0.1:8888/topologies?cluster=local
Topologies in local:
role     env      topology
-------  -------  --------------------
huijunw  default  hello-world-topology
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer  --tracker-url http://127.0.0.1:8888 topologies local
Usage: heron-explorer [OPTIONS] COMMAND [ARGS]...
Try 'heron-explorer --help' for help.

Error: no such option: --tracker-url

```
Should be `Usage: heron-explorer topologies CLUSTER[/ROLE[/ENV]] [OPTIONS]`rather than `Usage: heron-explorer topologies [OPTIONS] CLUSTER[/ROLE[/ENV]]`

`--tracker-url TEXT`, `TEXT` could be more descriptive

These issues exist as well for other sub-commands

3. looks like no difference of --component-type bolts/spouts/all
```
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer --verbose logical-plan local hello-world-topology --component-type bolts
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer --verbose logical-plan local hello-world-topology --component-type spouts
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer --verbose logical-plan local hello-world-topology --component-type all
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer --verbose logical-plan local hello-world-topology --component-type all --help
Usage: heron-explorer logical-plan [OPTIONS] CLUSTER[/ROLE[/ENV]] TOPOLOGY

Options:
  --config-path TEXT
  --tracker-url TEXT
  --component-type [all|spouts|bolts]
  --help                          Show this message and exit.

```

'consolidating the explorer functionality into the heron CLI'. - this question looks equivalent to 'shall we put all cli into one?' Originally `heron-explorer` was built equivalent to heron-ui, as an easy tool displaying topology stats, when some user has only access to terminals. It is optional, while `heron` is mandatory. Would like to see strong motivation to put `heron-explorer` into `heron`

**Comment by Code0x58** [comment]
Thanks for checking it out @huijunw!

1. Updated to default to WARNING and above, then can take -v/--verbose for INFO, and another -v/--verbose for DEBUG
2.
   * `click` always renders arguments after `[OPTIONS]`, but you can put the options after the arg (before the next subcommand)
   * when using `click` arguments/options for a subcommand must be after the given group/subcommand, and before the next subcommand. `heron-explorer  --tracker-url http://127.0.0.1:8888 topologies local` won't work because _topologies_ is the subcommand with the `--tracker-url`, so you'd have to do `heron-explorer topologies local --tracker-url http://127.0.0.1:8888` or `heron-explorer topologies --tracker-url http://127.0.0.1:8888 local`.
It felt a bit cleaner in the code to have `--tracker-url` and `--config-path` on the command, rather than the root level and having to pass them to the commands via the context dict
   * updated `--config-path` and `--tracker-url` to show the default, e.g.
        ```
        Usage: heron-explorer logical-plan [OPTIONS] CLUSTER[/ROLE[/ENV]] TOPOLOGY
        
          Show logical plan information for the given topology.
    
        Options:
          --config-path TEXT              Path to heron's config clusters config directory  [default: /home/vagrant/.heron/conf]
          --tracker-url TEXT              URL to a heron-tracker instance  [default: http://127.0.0.1:8888]
          --component-type [all|spouts|bolts]
                                          [default: all]
          --help                          Show this message and exit.
        ```
3. Fixed `--component-type` filter not being applied

----
re. the question, I was thinking of having both the CLI and web UI in the cam binary, but I didn't think much about the static files - I think I just wanted to get rid of tornado in `heron.tools.common.src.python.access`. I'm not sure merging them would be a good idea now, although having all CLI functions in one binary (i.e. `heron`) sounds tempting to me

**Comment by huijunwu** [comment]
Tested on MacOs. The --verbose does not work. The others look good
```
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer logical-plan local helloworld
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -
[tw-mbp-huijunw heron-github (explorer-cli)]$ ~/.heron/bin/heron-explorer --verbose logical-plan local helloworld
type    name        parallelism  input    output
------  --------  -------------  -------  --------
spout   word                  2  -        exclaim1
bolt    exclaim1              4  word     -

```

**Comment by Code0x58** [comment]
Thanks @huijunw! I think `-v` does work, there's just on _[INFO]_ level output for that command - adding `-vv` shows _[DEBUG]_ info

**Comment by huijunwu** [comment]
Thanks for clarification @Code0x58

**Pull request merged**
