### PR TITLE
move to protobuf version 3

### PR DESCRIPTION
**Pull request by kramasamy**

### CODE REVIEW

**Comment by maosongfu** [comment]
Please don't merge it unless everything is verified properly.

**Comment by objmagic** [comment]
@maosongfu agree

**Comment by objmagic** [comment]
would be good if @taishi8117 can profile again with this patch. We need to do experiment to get data.

**Comment by taishi8117** [comment]
@objmagic I'll do that once I'm done with integration tests for pyheron.

**Comment by kramasamy** [comment]
just the move to proto3 might not help - we need to enable the cpp implementation for python. will work on this in the next PR.

**Comment by congwang** [comment]
@kramasamy Any update on this?

**Comment by huijunwu** [comment]
https://github.com/apache/incubator-heron/pull/1591#issuecomment-613838466

**Pull request closed without merging**
