### PR TITLE
Update build-docker.sh

### PR DESCRIPTION
**Pull request by windhamwong**
--squash should be removed as this parameter is for experimental setup only.

### CODE REVIEW

**Comment by nwangtw** [comment]
I went back and forth about it too. :(  Without the flag the size is like doubled. @mjschmidt @joshfischer1108 how do you think about it?

**Comment by joshfischer1108** [comment]
If it doesn't cause any harm I don't see anything wrong with it.. We are building with Bazel `0.14.x`.  You could consider that as experimental too.

**Comment by joshfischer1108** [comment]
updated my comment for clarity.

**Comment by nwangtw** [comment]
KK. Thanks.

In my test I remember they both work ok, except the size is ~600m vs 1.2G.

I am fine either way but we dont really use docker image inside Twitter and it is ok if you guys feel it ok. I will approve it later if no objection by the end of day.

**Comment by joshfischer1108** [comment]
I would prefer to keep the `--squash` flag.  600m is better than 1.2G

**Comment by nwangtw** [comment]
Another option is to make it a parameter for the script and the default is without that flag.

The only problem I met with that flag is that Apache jenkins hosts don't have the flag enabled. This could be a problem for users' ci environment as well.

**Comment by nwangtw** [comment]
@windhamwong how do you think about making it a script argument?

**Comment by mjschmidt** [comment]
Sorry just seeing this. Seems like you guys figured out a fine solution

**Comment by mjschmidt** [comment]
I can live with it (:

**Comment by mjschmidt** [comment]
I can live with either.

**Comment by windhamwong** [comment]
Maybe we can add an option to the script that allows using this flag or not?

**Comment by windhamwong** [comment]
Let me check again and make an update to this

**Comment by windhamwong** [comment]
Updated the script with [-s|--squash] option.
Rephasing the default command help message

**Comment by nwangtw** [comment]
Build failure is caused by zookeeper library getting removed. Dmitry is working on the fix.

**Pull request merged**
