### PR TITLE
Add cluster to cmdline options

### PR DESCRIPTION
**Pull request by nwangtw**
This options could be useful in user topology.

### CODE REVIEW

**Comment by xiaoyao1991** [comment]
👍

**Comment by joshfischer1108** [comment]
@nwangtw  Was this change updated in the documentation anywhere?

**Comment by nwangtw** [comment]
> @nwangtw Was this change updated in the documentation anywhere?

Good point. I don't think the CLI document contains information about any of these options. Will see where to add them. Thanks.

**Comment by joshfischer1108** [comment]
Thank you sir

**Pull request merged**
