### PR TITLE
Topology package fetcher.

### PR DESCRIPTION
**Pull request by objmagic**
Add a topology fetcher in heron-client so that we can support fetching package from a remote location (for twitter internal package manager). This allows easier rollback, etc.

### CODE REVIEW

**Comment by nlu90** [comment]
@srkukarni The fetcher abstraction is to allow heron client to download topology files from remote storage like Packer within twitter and submit it. We need to update the heron client is because the topology's main method must be executed locally to generate information for topology submission.

**Comment by srkukarni** [comment]
@objmagic I understand that. However why are we duplicating functionlity that already exists in Java. Shouldn't the pathway be
1. If jar is regular file, continue as before
2. If jar is uri of some sort, invoke a downloader(analogous to the uploader). I believe the downloader functionality already exists in the java spi side of things.

**Comment by huijunw** [comment]
agree with @srkukarni 
re-use heron/heron/downloaders/ code

**Comment by huijunwu** [comment]
replaced by #2886. close this pr

**Pull request closed without merging**
