### PR TITLE
upgrade to Apache Bookkeeper 4.7.3 to fix DistributedLog based stateful storage

### LINKED ISSUE #3210: DistributedLog based stateful storage backend is not working
when we switch to `org.apache.heron.statefulstorage.dlog.DlogStorage` as the stateful topology state storage backend, the checkpointing manager is always throwing exception when it tries to save state for any heron instance into Bookkeeper cluster via the DistributedLog API.

We're testing using Heron v0.20.1-incubating-rc1, deployed on Kubernetes cluster, with a StatefulSet of 3 Bookkeeper pods and a StatefulSet of 3 Zookeeper pods.

The exception we got in the checkpointing manager log is:

`
[2019-03-10 20:05:59 +0000] [WARNING] org.apache.heron.ckptmgr.CheckpointManagerServer: Save checkpoint not successful for checkpointId 1552074656671682557-1552248359 component sum-bolt instanceId 0 
org.apache.heron.spi.statefulstorage.StatefulStorageException: Failed to persist checkpoint @ /arithmetic-progression-sum/1552074656671682557-1552248359/sum-bolt_0
	at org.apache.heron.statefulstorage.dlog.DlogStorage.storeCheckpoint(DlogStorage.java:148)
	at org.apache.heron.ckptmgr.CheckpointManagerServer.handleSaveInstanceStateRequest(CheckpointManagerServer.java:248)
	at org.apache.heron.ckptmgr.CheckpointManagerServer.onRequest(CheckpointManagerServer.java:108)
	at org.apache.heron.common.network.HeronServer.handlePacket(HeronServer.java:212)
	at org.apache.heron.common.network.HeronServer.handleRead(HeronServer.java:169)
	at org.apache.heron.common.basics.NIOLooper.handleSelectedKeys(NIOLooper.java:116)
	at org.apache.heron.common.basics.NIOLooper.access$000(NIOLooper.java:38)
	at org.apache.heron.common.basics.NIOLooper$1.run(NIOLooper.java:51)
	at org.apache.heron.common.basics.WakeableLooper.executeTasksOnWakeup(WakeableLooper.java:191)
	at org.apache.heron.common.basics.WakeableLooper.runOnce(WakeableLooper.java:110)
	at org.apache.heron.common.basics.WakeableLooper.loop(WakeableLooper.java:100)
	at org.apache.heron.ckptmgr.CheckpointManager.startAndLoop(CheckpointManager.java:175)
	at org.apache.heron.ckptmgr.CheckpointManager.main(CheckpointManager.java:263)
Caused by: org.apache.distributedlog.exceptions.ZKException: Failed to create log /distributedlog/arithmetic-progression-sum/1552074656671682557-1552248359/sum-bolt_0/<default> : NONODE
	at org.apache.distributedlog.impl.metadata.ZKLogStreamMetadataStore$3.processResult(ZKLogStreamMetadataStore.java:471)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$3$1.processResult(ZooKeeperClient.java:472)
	at dlshade.org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:658)
	at dlshade.org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
`

The cause of the issue is that when `DlogStorage` tries to open a new stream for writing each checkpoint data, the stream name is built in such a pattern:

/{topology name}/{checkpoint id}/{component name}_{task id}

the slash in the stream name makes DistributedLog interpreter it as namespace path, and in `apachedistributedlog/distributedlog:0.5.0`, stream name does not support slash.

The latest release of DistributedLog `apache/bookkeeper:4.9.0` is confirmed to have supported handling stream name with slash in it. Here's how I tested with it:

`docker run -it --rm --entrypoint bash apache/bookkeeper:4.9.0 bin/dlog local 7000`

Then in another terminal:

`simingweng$ docker exec -it 83ccfcd92948 bin/dlog tool create -u distributedlog://127.0.0.1:7000/messaging/distributedlog -r sub/path -e 1` 83ccfcd92948 is my running container id.

`docker exec -it 83ccfcd92948 bin/dlog tool list -u distributedlog://127.0.0.1:7000/messaging/distributedlog`

Streams under distributedlog://127.0.0.1:7000/messaging/distributedlog : 

`sub`

`docker exec -it 83ccfcd92948 bin/dlog tool list -u distributedlog://127.0.0.1:7000/messaging/distributedlog/sub`

Streams under distributedlog://127.0.0.1:7000/messaging/distributedlog/sub : 

`path1`

### PR DESCRIPTION
**Pull request by simingweng**
This fixes #3210 
1. upgrade to `apache/bookkeeper:4.7.3` to allow `DlogStorage` successfully persist stateful state to bookie
2. update variety of components dependent on DistributedLog API to `org.apache.distributedlog:distributedlog-core-shaded:4.7.3`
3. update those Kubernetes deployments that use Bookkeeper cluster

### CODE REVIEW

**Comment by simingweng** [comment]
@nwangtw

**Comment by nwangtw** [comment]
LGTM.

We don't use dlog internally.  @jerrypeng  do you have time to double check? Thanks!

**Comment by nwangtw** [comment]
Thanks @jerrypeng ~

**Comment by the-scott-hand** [comment]
has there been a new heron helm package released since these changes have been made? I would like to use the heron helm charts with apache bookkeeper 4.7.3, but I cant find any updated docs/packages. Just wanted to check before I resorted trying to package it myself. Thanks!

**Comment by nwangtw** [comment]
Not yet.

Dmitry is working on stmgr memory management and hopefully it fixes a mem leak. I think we can have another RC after the fix is merged: https://github.com/apache/incubator-heron/pull/3282

**Comment by the-scott-hand** [comment]
cool thanks, should i expect that to be put here? https://storage.googleapis.com/heron-charts

**Comment by nwangtw** [comment]
Interesting. I have no idea about that chart. :D  @kramasamy @jerrypeng  @nlu90 @huijunw any idea?

**Comment by the-scott-hand** [comment]
its referred to in this doc: https://apache.github.io/incubator-heron/docs/operators/deployment/schedulers/kubernetes-helm/

**Comment by joshfischer1108** [comment]
That was Streamlio’s chart repository.  I think we will have to do vote for an official release.  Otherwise you will have to build from source and create your own distribution.  We are in progress of updating the docs now.  There is an open PR for the website that has about half of the work done with a checklist of things to do for updating our docs.  Feel free to check it out.  The PR is here -> https://github.com/apache/incubator-heron/pull/3280

**Comment by the-scott-hand** [comment]
If I did want to build the chart myself, can I just replace VERSION with 0.17.8, remove ".template" from the Chart.yaml and values.yaml, put it in a folder called heron and run helm package? or are there more steps? asking because I did that and I'm getting "release heron failed: the server could not find the requested resource", wondering if I'm missing something.

Also as a side note, I have rook-ceph set up and was previously using that for my bookkeeper storage. Is there a way in the heron helm chart to change the storage class for the journal-disk and ledger-disk volumeClaimTemplates from default using the values.yaml?

Thanks again

**Comment by nwangtw** [comment]
I am wondering who is the owner of that file and if there is a log of changes in that file?

**Comment by simingweng** [comment]
I did adapt the relevant Helm templates in this PR. So, theoretically, you should be able to install the chart from locally. But, the tricky part is that there's no post-0.17.8 official release available in public, which means no heron post-0.17.8 docker image in public.

So, what we did in our deployment is to build heron RC release, push the docker image built to our own Artifactory repository, also push the generated maven artifacts there. Then, in our k8s cluster (we're on-promise), we configure the cluster to include our own Artifactory docker image repo.

Then we maintain a slightly different version of Helm chart based on the bare metal flavor of the templates available in this code base, because we're on-promise, and we don't need to care about GKE, AWS. So, our in house helm chart is simplified, but fairly close to the one in the source.

**Comment by the-scott-hand** [comment]
sorry if this isnt the right place for this discussion at this point. I was working through the issue, I've hit a couple issues looking at the code on master that maybe have been fixed in another branch I dont know about.

1. Baremetal refers to ledger disk, everything else refers to data-disk
trying to run helm chart with baremetal fails because it doesnt know what data-disk is
https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/bookie.yaml#L141

So I changed it to minikube and got past that error as a temp fix

2. my "the server could not find the requested resource" problem
I've narrowed my problem down to the line below
https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/tools.yaml#L18

my theory, is that the"-" in "{{- $platform" and the one on the other side of ".Values.apiServerMemory -}}" removes all white space between the comments and "apiVersion: v1". The problem, I think, is that this removes so much whitespace that "apiVersion: v1" actually gets commented out, like so:
"#  under the License.apiVersion: v1"
removing the first "-" from "{{- $platform" caused my error to go away, as well as copying the "apiVersion: v1" line and pasting it directly below itself.

That at least gets me to the point where I can helm install and get new errors

**Comment by the-scott-hand** [comment]
Added storageClassName: nameOfMyStorageClass directly after each of these lines with the same indentation to use rook-ceph for my storage, ended up needing it for bookie and zookeeper. still using "minikube" as my platform so I get the volumeClaimTemplate stuff. 

https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/zookeeper.yaml#L148
https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/bookie.yaml#L164
https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/bookie.yaml#L175

**Comment by the-scott-hand** [comment]
This line was also an issue for me:
https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/tools.yaml#L73

This seemed to work better for me:
command: ['sh', '-c', '/opt/bookkeeper/bin/dlog admin bind -l /ledgers -s {{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.clientPort }} -c distributedlog://{{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.clientPort }}/heron']

**Comment by the-scott-hand** [comment]
sorry again if im spamming this, I just want to keep track of these somewhere. 

On a somewhat more personal preference note, I don't like using the latest tag so that I can better keep track of what versions of things I'm running. It would be a "nice to have" to let the kubectl image be configurable in the values yaml as well
https://github.com/apache/incubator-heron/blob/6ce013cf262b8d413aec8c6e628ce363ef717ff1/deploy/kubernetes/helm/templates/tools.yaml#L161

**Comment by nwangtw** [comment]
No worries. If you like, feel free to file an issue and we can continue the discussion.

agree that "latest" can be tricky.

**Comment by the-scott-hand** [comment]
netcat (nc) is either not installed or not in the path of the container apache/bookkeeper:4.7.3, so the init container steps below fail:
https://github.com/apache/incubator-heron/blob/9ffeb39aec98d96caf2311b240216c8df6a4cc65/deploy/kubernetes/helm/templates/bookie.yaml#L104-L120

tried using the section from the minikube bookkeeper, I get "Error not able to create the directory /bookkeeper/data/journal" and "Error formatting journal directory failed"
https://github.com/apache/incubator-heron/blob/master/deploy/kubernetes/minikube/bookkeeper.yaml#L54-L62

ended up removing that section, that seemed to work

**Comment by the-scott-hand** [comment]
This line needs to change from org.apache.heron.uploader.dlog.DLUploader to com.twitter.heron.uploader.dlog.DLUploader ( see https://github.com/apache/incubator-heron/issues/2913#issuecomment-448798235)

https://github.com/apache/incubator-heron/blob/master/deploy/kubernetes/helm/templates/tools.yaml#L136

**Comment by the-scott-hand** [comment]
so after those changes, everything comes up healthy with a helm install! I now get an error when i try to submit a example topology where it says "Path length must be > 0". any thoughts?

**Comment by nwangtw** [comment]
Which topology? Maybe be good to start with a basic one, like word count.
Also it could be helpful to see if the topology runs ok locally.

Another guess might be the config.

**Pull request merged**
