### PR TITLE
fix get_heron_dir

### PR DESCRIPTION
**Pull request by thinker0**
Fix https://github.com/apache/incubator-heron/issues/3730

### CODE REVIEW

**Review by joshfischer1108 — APPROVED** [review]

**Comment by joshfischer1108** [comment]
Let's wait until CI passes before merging

**Comment by nicknezis** [comment]
My testing on another branch is currently failing and I think it might be related to this issue.

**Review by nicknezis — APPROVED** [review]

**Comment by nicknezis** [comment]
@thinker0 I'm still having issues with the build. I originally got this issue (https://github.com/python-zk/kazoo/pull/609) in the `heron-tracker`, but I bumped the version of Kazoo dependency to 2.8.0. That fixed that issue, but I now get the following:
```
kubectl -n pir logs heronkube-tools-bf7cf598-w46bs -c heron-tracker
[2021-11-12 21:28:15 +0000] [ERROR]: Exception while getting state_managers.
Traceback (most recent call last):
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/.bootstrap/pex/pex.py", line 476, in execute
    exit_value = self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/.bootstrap/pex/pex.py", line 401, in _wrap_coverage
    return runner(*args)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/.bootstrap/pex/pex.py", line 432, in _wrap_profiling
    return runner(*args)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/.bootstrap/pex/pex.py", line 532, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/.bootstrap/pex/pex.py", line 679, in execute_entry
    return self.execute_module(entry_point, alter_sys)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/.bootstrap/pex/pex.py", line 691, in execute_module
    runpy.run_module(module_name, run_name="__main__", alter_sys=alter_sys)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/tools/tracker/src/python/main.py", line 231, in <module>
    cli() # pylint: disable=no-value-for-parameter
  File "/root/.pex/installed_wheels/386b0f74344f046086c84bc4bc5c4f27f2f9a108/click-7.1.2-py2.py3-none-any.whl/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pex/installed_wheels/386b0f74344f046086c84bc4bc5c4f27f2f9a108/click-7.1.2-py2.py3-none-any.whl/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.pex/installed_wheels/386b0f74344f046086c84bc4bc5c4f27f2f9a108/click-7.1.2-py2.py3-none-any.whl/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pex/installed_wheels/386b0f74344f046086c84bc4bc5c4f27f2f9a108/click-7.1.2-py2.py3-none-any.whl/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/tools/tracker/src/python/main.py", line 204, in cli
    application = Application(config)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/tools/tracker/src/python/main.py", line 50, in __init__
    self.tracker.synch_topologies()
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/tools/tracker/src/python/tracker.py", line 121, in synch_topologies
    self.state_managers = statemanagerfactory.get_all_state_managers(self.config.statemgr_config)
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/statemgrs/src/python/statemanagerfactory.py", line 48, in get_all_state_managers
    raise ex
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/statemgrs/src/python/statemanagerfactory.py", line 43, in get_all_state_managers
    state_managers.extend(get_all_zk_state_managers(conf))
  File "/root/.pex/unzipped_pexes/3a087e21a1133580c59570c4b7dc76153a7fb1f5/heron/statemgrs/src/python/statemanagerfactory.py", line 72, in get_all_zk_state_managers
    tunnelhost = location['tunnelhost']
KeyError: 'tunnelhost'
```

**Comment by joshfischer1108** [comment]
@nicknezis It looks like the CI build failed on this PR.  I have not looked into the details of why it failed yet.   Can we revert the merge until proven it will pass?

**Comment by nicknezis** [comment]
Yes, but we also need to revert this issue: https://github.com/apache/incubator-heron/pull/3727

**Comment by thinker0** [comment]
it will fix

```
  pex_file = os.environ.get('PEX', None)
  if pex_file is not None:
    return normalized_class_path(str(Path(pex_file).resolve(strict=True).parent.parent))
```

**Comment by thinker0** [comment]
https://github.com/apache/incubator-heron/pull/3734

**Comment by nicknezis** [comment]
That fixed it. Thank you!

**Pull request merged**
